const WORDS = [
  { "en": "slap", "phonetic": "/slæp/", "zh": "vt.拍,掌击,拍击 n.拍,掌击,拍击" },
  { "en": "dispatch", "phonetic": "/dɪˈspætʃ/", "zh": "vt.分派,派遣 n.派遣,急件" },
  { "en": "smuggle", "phonetic": "/ˈsmʌɡl/", "zh": "vt. 走私；偷运 vi. 走私，私运；偷带" },
  { "en": "nourish", "phonetic": "/ˈnɜːrɪʃ/", "zh": "vt. 滋养；怀有；使健壮" },
  { "en": "fling", "phonetic": "/flɪŋ/", "zh": "vt. 掷，抛；嘲笑；使陷入；轻蔑地投射；猛动 n. 掷，抛；嘲弄；急冲 vi. 猛冲，急行" },
  { "en": "heal", "phonetic": "/hiːl/", "zh": "vt. 治愈，痊愈；和解 vi. 痊愈" },
  { "en": "fabricate", "phonetic": "/ˈfæbrɪkeɪt/", "zh": "vt. 制造；伪造；装配" },
  { "en": "designate", "phonetic": "/ˈdezɪɡneɪt/", "zh": "vt. 指定；指派；标出；把…定名为 adj. 指定的；选定的" },
  { "en": "uphold", "phonetic": "/ʌpˈhoʊld/", "zh": "vt. 支撑；鼓励；赞成；举起" },
  { "en": "convict", "phonetic": "/kənˈvɪkt; ˈkɑnvɪkt/", "zh": "vt. 证明…有罪；宣告…有罪 n. 罪犯" },
  { "en": "testify", "phonetic": "/ˈtestɪfaɪ/", "zh": "vt. 证明，证实；作证 vi. 作证；证明" },
  { "en": "afflict", "phonetic": "/əˈflɪkt/", "zh": "vt. 折磨；使痛苦；使苦恼" },
  { "en": "summon", "phonetic": "/ˈsʌmən/", "zh": "vt. 召唤；召集；鼓起；振作" },
  { "en": "inflict", "phonetic": "/ɪnˈflɪkt/", "zh": "vt. 造成；使遭受（损伤、痛苦等）；给予（打击等）" },
  { "en": "pose", "phonetic": "/poʊz/", "zh": "vt. 造成，形成；摆姿势；装模作样；提出…讨论 vi. 摆姿势；佯装；矫揉造作 n. 姿势，姿" },
  { "en": "ponder", "phonetic": "/ˈpɑːndər/", "zh": "vt. 仔细考虑；衡量 vi. 考虑；沉思" },
  { "en": "resent", "phonetic": "/rɪˈzent/", "zh": "vt. 怨恨；愤恨；厌恶" },
  { "en": "induce", "phonetic": "/ɪnˈduːs/", "zh": "vt. 诱导；引起；引诱；感应" },
  { "en": "originate", "phonetic": "/əˈrɪdʒɪneɪt/", "zh": "vt. 引起；创作 vi. 发源；发生；起航" },
  { "en": "evoke", "phonetic": "/ɪˈvoʊk/", "zh": "vt. 引起，唤起；博得" },
  { "en": "suppress", "phonetic": "/səˈpres/", "zh": "vt. 抑制；镇压；废止" },
  { "en": "inhibit", "phonetic": "/ɪnˈhɪbɪt/", "zh": "vt. 抑制；禁止" },
  { "en": "disguise", "phonetic": "/dɪsˈɡaɪz/", "zh": "vt. 掩饰；假装；隐瞒 n. 伪装；假装；用作伪装的东西" },
  { "en": "prolong", "phonetic": "/prəˈlɔːŋ/", "zh": "vt. 延长；拖延" },
  { "en": "overwhelm", "phonetic": "/ˌoʊvərˈwelm/", "zh": "vt. 淹没；压倒；受打击；覆盖；压垮" },
  { "en": "oppress", "phonetic": "/əˈpres/", "zh": "vt. 压迫，压抑；使……烦恼；使……感到沉重" },
  { "en": "proclaim", "phonetic": "/prəˈkleɪm/", "zh": "vt. 宣告，公布；声明；表明；赞扬" },
  { "en": "visualize", "phonetic": "/ˈvɪʒuəlaɪz/", "zh": "vt. 形象，形象化；想像，设想 vi. 显现" },
  { "en": "extinguish", "phonetic": "/ɪkˈstɪŋɡwɪʃ/", "zh": "vt. 熄灭；压制；偿清" },
  { "en": "quench", "phonetic": "/kwentʃ/", "zh": "vt. 熄灭，[机] 淬火；解渴；结束；冷浸 vi. 熄灭；平息" },
  { "en": "assimilate", "phonetic": "/əˈsɪməleɪt/", "zh": "vt. 吸收；使同化；把…比作；使相似 vi. 吸收；同化" },
  { "en": "overhear", "phonetic": "/ˌoʊvərˈhɪr/", "zh": "vt. 无意中听到；偷听 vi. 无意中听到；偷听到" },
  { "en": "contaminate", "phonetic": "/kənˈtæmɪneɪt/", "zh": "vt. 污染，弄脏" },
  { "en": "assert", "phonetic": "/əˈsɜːrt/", "zh": "vt. 维护，坚持；断言；主张；声称" },
  { "en": "violate", "phonetic": "/ˈvaɪəleɪt/", "zh": "vt. 违反；侵犯，妨碍；亵渎" },
  { "en": "jeopardize", "phonetic": "/ˈdʒepərdaɪz/", "zh": "vt. 危害；使陷危地；使受危困" },
  { "en": "propel", "phonetic": "/prəˈpel/", "zh": "vt. 推进；驱使；激励；驱策" },
  { "en": "nominate", "phonetic": "/ˈnɑːmɪneɪt/", "zh": "vt. 推荐；提名；任命；指定" },
  { "en": "snap", "phonetic": "/snæp/", "zh": "vt. 突然折断，拉断；猛咬；啪地关上 vi. 咬；厉声说；咯嗒一声关上 n. 猛咬；劈啪声；突" },
  { "en": "notify", "phonetic": "/ˈnoʊtɪfaɪ/", "zh": "vt. 通告，通知；公布" },
  { "en": "lick", "phonetic": "/lɪk/", "zh": "vt. 舔；卷过；鞭打 vt. （非正式）战胜 vi. 舔；轻轻拍打 n. 舔；打；少许" },
  { "en": "enhance", "phonetic": "/ɪnˈhæns/", "zh": "vt. 提高；加强；增加" },
  { "en": "negotiate", "phonetic": "/nɪˈɡoʊʃieɪt/", "zh": "vt. 谈判，商议；转让；越过 vi. 谈判，交涉" },
  { "en": "impair", "phonetic": "/ɪmˈper/", "zh": "vt. 损害；削弱；减少" },
  { "en": "shrug", "phonetic": "/ʃrʌɡ/", "zh": "vt. 耸肩，耸肩表示 n. 耸肩 vi. 耸肩" },
  { "en": "rip", "phonetic": "/rɪp/", "zh": "vt. 撕；锯 vi. 裂开，被撕裂 n. 裂口，裂缝" },
  { "en": "preach", "phonetic": "/priːtʃ/", "zh": "vt. 说教；讲道；鼓吹；传道；反复灌输 vi. 说教；讲道；鼓吹；宣扬 n. 说教" },
  { "en": "confer", "phonetic": "/kənˈfɜːr/", "zh": "vt. 授予；给予 vi. 协商" },
  { "en": "reap", "phonetic": "/riːp/", "zh": "vt. 收获，获得；收割 vi. 收割，收获" },
  { "en": "terminate", "phonetic": "/ˈtɜːrmɪneɪt/", "zh": "vt. 使终止；使结束；解雇 vi. 结束，终止；结果 adj. 结束的" },
  { "en": "reconcile", "phonetic": "/ˈrekənsaɪl/", "zh": "vt. 使一致；使和解；调停，调解；使顺从" },
  { "en": "entail", "phonetic": "/ɪnˈteɪl/", "zh": "vt. 使需要，必需；承担；遗传给；蕴含 n. 引起；需要；继承" },
  { "en": "startle", "phonetic": "/ˈstɑːrtl/", "zh": "vt. 使吓一跳；使惊奇 vi. 惊吓；惊跳；惊奇 n. 惊愕；惊恐" },
  { "en": "stabilize", "phonetic": "/ˈsteɪbəlaɪz/", "zh": "vt. 使稳固，使安定 vi. 稳定，安定" },
  { "en": "ventilate", "phonetic": "/ˈventɪleɪt/", "zh": "vt. 使通风；给…装通风设备；宣布" },
  { "en": "suffice", "phonetic": "/səˈfaɪs/", "zh": "vt. 使满足；足够…用；合格 vi. 足够；有能力" },
  { "en": "perish", "phonetic": "/ˈperɪʃ/", "zh": "vt. 使麻木；毁坏 vi. 死亡；毁灭；腐烂；枯萎" },
  { "en": "paralyze", "phonetic": "/ˈpærəˌlaɪz/", "zh": "vt. 使麻痹；使瘫痪" },
  { "en": "perplex", "phonetic": "/pərˈpleks/", "zh": "vt. 使困惑，使为难；使复杂化" },
  { "en": "minimize", "phonetic": "/ˈmɪnɪmaɪz/", "zh": "vt. 使减到最少；小看，极度轻视 vi. 最小化" },
  { "en": "converge", "phonetic": "/kənˈvɜːrdʒ/", "zh": "vt. 使汇聚 vi. 聚集；靠拢；收敛" },
  { "en": "segregate", "phonetic": "/ˈseɡrɪɡeɪt/", "zh": "vt. 使隔离；使分离；在…实行种族隔离" },
  { "en": "grieve", "phonetic": "/ɡriːv/", "zh": "vt. 使悲伤，使苦恼 vi. 悲痛，哀悼" },
  { "en": "invert", "phonetic": "/ɪnˈvɜːrt/", "zh": "vt. 使…转化；使…颠倒；使…反转；使…前后倒置 n. 颠倒的事物；倒置物；倒悬者 adj." },
  { "en": "integrate", "phonetic": "/ˈɪntɪɡreɪt/", "zh": "vt. 使…完整；使…成整体；求…的积分；表示…的总和 vi. 求积分；取消隔离；成为一体" },
  { "en": "adj.", "phonetic": "", "zh": "整合的；完全的 n. 一体化；集成体" },
  { "en": "baffle", "phonetic": "/ˈbæfl/", "zh": "vt. 使…困惑；使…受挫折；用挡板控制 n. 挡板；困惑 vi. 做徒劳挣扎" },
  { "en": "implement", "phonetic": "/ˈɪmplɪmənt/", "zh": "vt. 实施，执行；实现，使生效 n. 工具，器具；手段" },
  { "en": "transcend", "phonetic": "/trænˈsend/", "zh": "vt. 胜过，超越" },
  { "en": "contrive", "phonetic": "/kənˈtraɪv/", "zh": "vt. 设计；发明；图谋 vi. 谋划；设法做到" },
  { "en": "ascertain", "phonetic": "/ˌæsərˈteɪn/", "zh": "vt. 确定；查明；探知" },
  { "en": "tease", "phonetic": "/tiːz/", "zh": "vt. 取笑；戏弄；梳理；欺负；强求；使起毛 n. 戏弄；爱纠缠的小孩；挑逗者；卖弄风骚的" },
  { "en": "constrain", "phonetic": "/kənˈstreɪn/", "zh": "vt. 驱使；强迫；束缚" },
  { "en": "provoke", "phonetic": "/prəˈvoʊk/", "zh": "vt. 驱使；激怒；煽动；惹起" },
  { "en": "despise", "phonetic": "/dɪˈspaɪz/", "zh": "vt. 轻视，鄙视" },
  { "en": "corrode", "phonetic": "/kəˈroʊd/", "zh": "vt. 侵蚀；损害 vi. 受腐蚀；起腐蚀作用" },
  { "en": "denounce", "phonetic": "/dɪˈnaʊns/", "zh": "vt. 谴责；告发；公然抨击；通告废除" },
  { "en": "disrupt", "phonetic": "/dɪsˈrʌpt/", "zh": "vt. 破坏；使瓦解；使分裂；使中断；使陷于混乱 adj. 分裂的，中断的；分散的" },
  { "en": "undermine", "phonetic": "/ˌʌndərˈmaɪn/", "zh": "vt. 破坏，渐渐破坏；挖掘地基" },
  { "en": "stagger", "phonetic": "/ˈstæɡər/", "zh": "vt. 蹒跚；使交错；使犹豫 vi. 蹒跚；犹豫 n. 蹒跚；交错安排 adj. 交错的；错开的" },
  { "en": "preclude", "phonetic": "/prɪˈkluːd/", "zh": "vt. 排除；妨碍；阻止" },
  { "en": "simulate", "phonetic": "/ˈsɪmjuleɪt/", "zh": "vt. 模仿；假装；冒充 adj. 模仿的；假装的" },
  { "en": "depict", "phonetic": "/dɪˈpɪkt/", "zh": "vt. 描述；描画" },
  { "en": "portray", "phonetic": "/pɔːrˈtreɪ/", "zh": "vt. 描绘；扮演" },
  { "en": "indulge", "phonetic": "/ɪnˈdʌldʒ/", "zh": "vt. 满足；纵容；使高兴；使沉迷于… vi. 沉溺；满足；放任" },
  { "en": "precede", "phonetic": "/prɪˈsiːd/", "zh": "vt. 领先，在…之前；优于，高于 vi. 领先，在前面" },
  { "en": "quantify", "phonetic": "/ˈkwɑːntɪfaɪ/", "zh": "vt. 量化；为…定量；确定数量 vi. 量化；定量" },
  { "en": "exemplify", "phonetic": "/ɪɡˈzemplɪfaɪ/", "zh": "vt. 例证；例示" },
  { "en": "dissipate", "phonetic": "/ˈdɪsɪpeɪt/", "zh": "vt. 浪费；使…消散 vi. 驱散；放荡" },
  { "en": "sue", "phonetic": "/suː/", "zh": "vt. 控告；请求 vi. 控告；提出请求" },
  { "en": "terrify", "phonetic": "/ˈterɪfaɪ/", "zh": "vt. 恐吓；使恐怖；使害怕" },
  { "en": "intimidate", "phonetic": "/ɪnˈtɪmɪdeɪt/", "zh": "vt. 恐吓，威胁；胁迫" },
  { "en": "reclaim", "phonetic": "/rɪˈkleɪm/", "zh": "vt. 开拓；回收再利用；改造某人，使某人悔改 vi. 抗议，喊叫 n. 改造，感化；再生胶" },
  { "en": "discern", "phonetic": "/dɪˈsɜːrn/", "zh": "vt. 觉察出；识别；了解；隐约看见 vi. 辨别" },
  { "en": "heave", "phonetic": "/hiːv/", "zh": "vt. 举起；使起伏；投掷；恶心；发出（叹息等） vi. 起伏；举起；喘息；呕吐 n. 举起；起" },
  { "en": "purify", "phonetic": "/ˈpjʊrɪfaɪ/", "zh": "vt. 净化；使纯净 vi. 净化；变纯净" },
  { "en": "saturate", "phonetic": "/ˈsætʃəreɪt/", "zh": "vt. 浸透，使湿透；使饱和，使充满 adj. 浸透的，饱和的；深颜色的" },
  { "en": "plead", "phonetic": "/pliːd/", "zh": "vt. 借口；为...辩护；托称 vi. 恳求；辩护" },
  { "en": "alleviate", "phonetic": "/əˈliːvieɪt/", "zh": "vt. 减轻，缓和" },
  { "en": "postulate", "phonetic": "/ˈpɑːstʃəleɪt/", "zh": "vt. 假定；要求；视…为理所当然 n. 基本条件；假定" },
  { "en": "presume", "phonetic": "/prɪˈzuːm/", "zh": "vt. 假定；推测；擅自；意味着 vi. 相信；擅自行为" },
  { "en": "aggravate", "phonetic": "/ˈæɡrəveɪt/", "zh": "vt. 加重；使恶化；激怒" },
  { "en": "repel", "phonetic": "/rɪˈpel/", "zh": "vt. 击退；抵制；使厌恶；使不愉快" },
  { "en": "conceive", "phonetic": "/kənˈsiːv/", "zh": "vt. 怀孕；构思；以为；持有 vi. 怀孕；设想；考虑" },
  { "en": "merge", "phonetic": "/mɜːrdʒ/", "zh": "vt. 合并；使合并；吞没 vi. 合并；融合" },
  { "en": "formulate", "phonetic": "/ˈfɔːrmjuleɪt/", "zh": "vt. 规划；用公式表示；明确地表达" },
  { "en": "ascribe", "phonetic": "/əˈskraɪb/", "zh": "vt. 归因于；归咎于" },
  { "en": "update", "phonetic": "/ˌʌpˈdeɪt/", "zh": "vt. 更新；校正，修正；使现代化 n. 更新；现代化" },
  { "en": "insulate", "phonetic": "/ˈɪnsəleɪt/", "zh": "vt. 隔离，使孤立；使绝缘，使隔热" },
  { "en": "impart", "phonetic": "/ɪmˈpɑːrt/", "zh": "vt. 告知，传授；透露，透漏；赋予，给予（尤指抽象事物）" },
  { "en": "rectify", "phonetic": "/ˈrektɪfaɪ/", "zh": "vt. 改正；精馏；整流" },
  { "en": "endow", "phonetic": "/ɪnˈdaʊ/", "zh": "vt. 赋予；捐赠；天生具有" },
  { "en": "radiate", "phonetic": "/ˈreɪdieɪt/", "zh": "vt. 辐射；传播；流露；发射；广播 vi. 辐射；流露；发光；从中心向各方伸展 adj. 辐" },
  { "en": "shatter", "phonetic": "/ˈʃætər/", "zh": "vt. 粉碎；打碎；破坏；破掉；使散开 vi. 粉碎；损坏；落叶 n. 碎片；乱七八糟的状态" },
  { "en": "disperse", "phonetic": "/dɪˈspɜːrs/", "zh": "vt. 分散；使散开；传播 vi. 分散 adj. 分散的" },
  { "en": "graze", "phonetic": "/ɡreɪz/", "zh": "vt. 放牧；擦伤 vi. 吃草；擦伤 n. 放牧；轻擦" },
  { "en": "magnify", "phonetic": "/ˈmæɡnɪfaɪ/", "zh": "vt. 放大；赞美；夸大 vi. 放大；有放大能力" },
  { "en": "hamper", "phonetic": "/ˈhæmpər/", "zh": "vt. 妨碍；束缚；使困累 n. 食盒，食篮；阻碍物" },
  { "en": "contradict", "phonetic": "/ˌkɑːntrəˈdɪkt/", "zh": "vt. 反驳；否定；与…矛盾；与…抵触 vi. 反驳；否认；发生矛盾" },
  { "en": "refute", "phonetic": "/rɪˈfjuːt/", "zh": "vt. 反驳，驳斥；驳倒" },
  { "en": "mobilize", "phonetic": "/ˈmoʊbəlaɪz/", "zh": "vt. 动员，调动；集合，组织；使…流通；使…松动 vi. 组织；动员起来" },
  { "en": "hurl", "phonetic": "/hɜːrl/", "zh": "vt. 丢下；用力投掷；愤慨地说出 vi. 猛投；猛掷 n. 用力的投掷" },
  { "en": "ignite", "phonetic": "/ɪɡˈnaɪt/", "zh": "vt. 点燃；使燃烧；使激动 vi. 点火；燃烧" },
  { "en": "underestimate", "phonetic": "/ˌʌndərˈestɪmeɪt/", "zh": "vt. 低估；看轻 n. 低估" },
  { "en": "unfold", "phonetic": "/ʌnˈfoʊld/", "zh": "vt. 打开；呈现 vi. 展开；显露" },
  { "en": "frustrate", "phonetic": "/ˈfrʌstreɪt/", "zh": "vt. 挫败；阻挠；使感到灰心 vi. 失败；受挫 adj. 挫败的；无益的" },
  { "en": "facilitate", "phonetic": "/fəˈsɪlɪteɪt/", "zh": "vt. 促进；帮助；使容易" },
  { "en": "irritate", "phonetic": "/ˈɪrɪteɪt/", "zh": "vt. 刺激，使兴奋；激怒 vi. 引起恼怒，引起不愉快" },
  { "en": "inaugurate", "phonetic": "/ɪˈnɔːɡjəreɪt/", "zh": "vt. 创新；开辟；开创；举行开幕典礼；举行就职典礼" },
  { "en": "propagate", "phonetic": "/ˈprɑːpəɡeɪt/", "zh": "vt. 传播；传送；繁殖；宣传 vi. 繁殖；增殖" },
  { "en": "elicit", "phonetic": "/ɪˈlɪsɪt/", "zh": "vt. 抽出，引出；引起" },
  { "en": "concede", "phonetic": "/kənˈsiːd/", "zh": "vt. 承认；退让；给予，容许 vi. 让步" },
  { "en": "contemplate", "phonetic": "/ˈkɑːntəmpleɪt/", "zh": "vt. 沉思；注视；思忖；预期 vi. 冥思苦想；深思熟虑" },
  { "en": "immerse", "phonetic": "/ɪˈmɜːrs/", "zh": "vt. 沉浸；使陷入" },
  { "en": "surpass", "phonetic": "/sərˈpæs/", "zh": "vt. 超越；胜过，优于；非…所能办到或理解" },
  { "en": "haunt", "phonetic": "/hɔːnt/", "zh": "vt. 常出没于…；萦绕于…；经常去… vi. 出没；作祟 n. 栖息地；常去的地方" },
  { "en": "illuminate", "phonetic": "/ɪˈluːmɪneɪt/", "zh": "vt. 阐明，说明；照亮；使灿烂；用灯装饰 vi. 照亮" },
  { "en": "reckon", "phonetic": "/ˈrekən/", "zh": "vt. 测算，估计；认为；计算 vi. 估计；计算；猜想，料想" },
  { "en": "manipulate", "phonetic": "/məˈnɪpjuleɪt/", "zh": "vt. 操纵；操作；巧妙地处理；篡改" },
  { "en": "signify", "phonetic": "/ˈsɪɡnɪfaɪ/", "zh": "vt. 表示；意味；预示 vi. 有重要性；要紧；冒充内行" },
  { "en": "denote", "phonetic": "/dɪˈnoʊt/", "zh": "vt. 表示，指示" },
  { "en": "compile", "phonetic": "/kəmˈpaɪl/", "zh": "vt. 编译；编制；编辑；[图情] 汇编" },
  { "en": "avert", "phonetic": "/əˈvɜːrt/", "zh": "vt. 避免，防止；转移" },
  { "en": "recite", "phonetic": "/rɪˈsaɪt/", "zh": "vt. 背诵；叙述；列举 vi. 背诵；叙述" },
  { "en": "withhold", "phonetic": "/wɪðˈhəʊld/", "zh": "vt. 保留，不给；隐瞒；抑制 vi. 忍住；克制" },
  { "en": "conserve", "phonetic": "/kənˈsɜːrv/", "zh": "vt. 保存；将…做成蜜饯；使守恒 n. 果酱；蜜饯" },
  { "en": "streamline", "phonetic": "/ˈstriːmlaɪn/", "zh": "vt. 把…做成流线型；使现代化；组织；使合理化；使简单化 n. 流线；流线型 adj." },
  { "en": "retrieve", "phonetic": "/rɪˈtriːv/", "zh": "vt. [计] 检索；恢复；重新得到 vi. 找回猎物 n. [计] 检索；恢复，取回" },
  { "en": "reside", "phonetic": "/rɪˈzaɪd/", "zh": "vi. 住，居住；属于" },
  { "en": "preside", "phonetic": "/prɪˈzaɪd/", "zh": "vi. 主持，担任会议主席 vt. 管理" },
  { "en": "distil", "phonetic": "/dɪˈstɪl/", "zh": "vi. 蒸馏；提炼；渗出 vt. 蒸馏；提取…的精华；使渗出" },
  { "en": "intensify", "phonetic": "/ɪnˈtensɪfaɪ/", "zh": "vi. 增强，强化；变激烈 vt. 使加强，使强化；使变激烈" },
  { "en": "augment", "phonetic": "/ɔːɡˈment/", "zh": "vi. 增加；增大 vt. 增加；增大 n. 增加；增大" },
  { "en": "migrate", "phonetic": "/ˈmaɪɡreɪt/", "zh": "vi. 移动；随季节而移居；移往 vt. 使移居；使移植" },
  { "en": "revolve", "phonetic": "/rɪˈvɑːlv/", "zh": "vi. 旋转；循环出现；反复考虑 vt. 使…旋转；使…循环；反复考虑 n. 旋转；循环；旋转" },
  { "en": "speculate", "phonetic": "/ˈspekjuleɪt/", "zh": "vi. 推测；投机；思索 vt. 推断" },
  { "en": "skip", "phonetic": "/skɪp/", "zh": "vi. 跳跃；跳绳；遗漏；跳读 vt. 跳过；遗漏 n. 跳跃；跳读" },
  { "en": "tumble", "phonetic": "/ˈtʌmbl/", "zh": "vi. 摔倒；倒塌；滚动；打滚；仓惶地行动 vt. 使摔倒；使滚翻；弄乱 n. 跌倒；翻筋斗；跌" },
  { "en": "lubricate", "phonetic": "/ˈluːbrɪkeɪt/", "zh": "vi. 润滑；涂油；起润滑剂作用 vt. 使…润滑；给…加润滑油" },
  { "en": "expire", "phonetic": "/ɪkˈspaɪər/", "zh": "vi. 期满；终止；死亡；呼气 vt. 呼出（空气）" },
  { "en": "hover", "phonetic": "/ˈhʌvər/", "zh": "vi. 盘旋，翱翔；徘徊 n. 徘徊；盘旋；犹豫 vt. 孵；徘徊在…近旁" },
  { "en": "linger", "phonetic": "/ˈlɪŋɡər/", "zh": "vi. 徘徊；苟延残喘；磨蹭 vt. 消磨；缓慢度过" },
  { "en": "strive", "phonetic": "/straɪv/", "zh": "vi. 努力；奋斗；抗争" },
  { "en": "grope", "phonetic": "/ɡroʊp/", "zh": "vi. 摸索；探索 vt. 摸索 n. 摸索；触摸" },
  { "en": "dwell", "phonetic": "/dwel/", "zh": "vi. 居住；存在于；细想某事" },
  { "en": "contend", "phonetic": "/kənˈtend/", "zh": "vi. 竞争；奋斗；斗争；争论 vt. 主张；为...斗争" },
  { "en": "refrain", "phonetic": "/rɪˈfreɪn/", "zh": "vi. 节制，克制；避免；制止 n. 叠句，副歌；重复" },
  { "en": "soar", "phonetic": "/sɔːr/", "zh": "vi. 急升，激增；高飞；升空；翱翔；（树木、建筑物等）高耸；（情绪）高涨 n. 高飞；高涨" },
  { "en": "mingle", "phonetic": "/ˈmɪŋɡl/", "zh": "vi. 混合；交往 vt. 使混合；使相混" },
  { "en": "glide", "phonetic": "/ɡlaɪd/", "zh": "vi. 滑翔；滑行；悄悄地走；消逝 vt. 使滑行；使滑动 n. 滑翔；滑行；滑移；滑音" },
  { "en": "mutter", "phonetic": "/ˈmʌtər/", "zh": "vi. 咕哝；喃喃自语 vt. 咕哝；抱怨地说；低声含糊地说 n. 咕哝；喃喃低语" },
  { "en": "rejoice", "phonetic": "/rɪˈdʒɔɪs/", "zh": "vi. 高兴；庆祝 vt. 使高兴" },
  { "en": "revive", "phonetic": "/rɪˈvaɪv/", "zh": "vi. 复兴；复活；苏醒；恢复精神 vt. 使复兴；使苏醒；回想起；重演，重播" },
  { "en": "recur", "phonetic": "/rɪˈkɜːr/", "zh": "vi. 复发；重现；采用；再来；循环；递归" },
  { "en": "conform", "phonetic": "/kənˈfɔːrm/", "zh": "vi. 符合；遵照；适应环境 vt. 使遵守；使一致；使顺从 adj. 一致的；顺从的" },
  { "en": "deteriorate", "phonetic": "/dɪˈtɪriəreɪt/", "zh": "vi. 恶化，变坏 vt. 恶化" },
  { "en": "subscribe", "phonetic": "/səbˈskraɪb/", "zh": "vi. 订阅；捐款；认购；赞成；签署 vt. 签署；赞成；捐助" },
  { "en": "mediate", "phonetic": "/ˈmiːdieɪt/", "zh": "vi. 调解；斡旋；居中 vt. 调停；传达 adj. 间接的；居间的" },
  { "en": "culminate", "phonetic": "/ˈkʌlmɪneɪt/", "zh": "vi. 到绝顶；达到高潮；达到顶点 vt. 使结束；使达到高潮" },
  { "en": "yell", "phonetic": "/jel/", "zh": "vi. 大叫，叫喊 n. 喊声，叫声 vt. 喊叫着说" },
  { "en": "poke", "phonetic": "/poʊk/", "zh": "vi. 刺，捅；戳；伸出；刺探；闲荡 vt. 刺，捅；戳；拨开 n. 戳；刺；袋子；懒汉" },
  { "en": "gasp", "phonetic": "/ɡæsp/", "zh": "vi. 喘气；喘息；渴望 vt. 气喘吁吁地说；喘着气说话 n. 喘气" },
  { "en": "stumble", "phonetic": "/ˈstʌmbl/", "zh": "vi. 踌躇，蹒跚；失足；犯错 vt. 使…困惑；使…绊倒 n. 绊倒；蹒跚而行" },
  { "en": "hinder", "phonetic": "/ˈhɪndər/", "zh": "vi. 成为阻碍 vt. 阻碍；打扰 adj. 后面的" },
  { "en": "repay", "phonetic": "/rɪˈpeɪ/", "zh": "vi. 偿还；报答；报复 vt. 回报；报复；付还" },
  { "en": "fluctuate", "phonetic": "/ˈflʌktʃueɪt/", "zh": "vi. 波动；涨落；动摇 vt. 使波动；使动摇" },
  { "en": "knit", "phonetic": "/nɪt/", "zh": "vi. 编织；结合；皱眉 vt. 编织；结合 n. 编织衣物；编织法" },
  { "en": "commute", "phonetic": "/kəˈmjuːt/", "zh": "vi. （搭乘车、船等）通勤；代偿 vt. 减刑；交换；用……交换；使……变成 n. 通勤" },
  { "en": "rally", "phonetic": "/ˈræli/", "zh": "v.重整旗鼓,给予新力量,(使)恢复健康,力量,决心,集结 n.集会" },
  { "en": "toss", "phonetic": "/tɔːs/", "zh": "v.投,掷" },
  { "en": "snatch", "phonetic": "/snætʃ/", "zh": "v.攫取 n.攫取" },
  { "en": "smash", "phonetic": "/smæʃ/", "zh": "v.打碎,粉碎 n.打碎,粉碎 adj.出色的" },
  { "en": "mock", "phonetic": "/mɑːk/", "zh": "v.嘲笑,骗,挫败,嘲弄 adj.假的 n.嘲弄,模仿,仿制品" },
  { "en": "overlap", "phonetic": "/ˌoʊvərˈlæp/", "zh": "v.(与...)交迭" },
  { "en": "whirl", "phonetic": "/wɜːrl/", "zh": "v.(使)旋转,急动,急走 n.旋转,—连串快速的活动" },
  { "en": "rot", "phonetic": "/rɑːt/", "zh": "v.(使)腐烂,(使)腐败 n.腐烂,腐败" },
  { "en": "unify", "phonetic": "/ˈjuːnɪfaɪ/", "zh": "v. 整合，联合；统一，使成一体" },
  { "en": "recruit", "phonetic": "/rɪˈkruːt/", "zh": "v. 征募；聘用；通过招募组建；补充；（非正式）说服；（使）恢复健康 n. 招聘；新兵；" },
  { "en": "incur", "phonetic": "/ɪnˈkɜːr/", "zh": "v. 招致，遭受；引致，带来……" },
  { "en": "avail", "phonetic": "/əˈveɪl/", "zh": "v. 有助于；（使）对某人有利 n. 效用，利益" },
  { "en": "transplant", "phonetic": "/trænsˈplɑːnt/", "zh": "v. 移植；移栽；使移居 n. 移植；移植器官；被移植物；移居者" },
  { "en": "dilute", "phonetic": "/daɪˈluːt/", "zh": "v. 稀释，冲淡；削弱；变稀薄，变淡 adj. 稀释的；淡的；（颜色、光线）浅的" },
  { "en": "tow", "phonetic": "/toʊ/", "zh": "v. 拖；牵引；拽 n. 拖；麻的粗纤维；拖具" },
  { "en": "overthrow", "phonetic": "/ˌoʊvərˈθroʊ/", "zh": "v. 推翻，倾覆；瓦解；投（球）过远；背弃 n. 推翻，打倒，倾覆；投球过猛；" },
  { "en": "degenerate", "phonetic": "/dɪˈdʒenəreɪt/", "zh": "v. 使退化；恶化；堕落 adj. 退化的；堕落的；退化的；简并的 n. 堕落的人" },
  { "en": "hoist", "phonetic": "/hɔɪst/", "zh": "v. 升起，吊起；抬高，举起 n. 起重机；吊车；升降机；升起，增加；信号旗；旗宽" },
  { "en": "envisage", "phonetic": "/ɪnˈvɪzɪdʒ/", "zh": "v. 设想，想像；正视，面对" },
  { "en": "embark", "phonetic": "/ɪmˈbɑːrk/", "zh": "v. 上船（或飞机）；（使）上船（或登记）；从事" },
  { "en": "tilt", "phonetic": "/tɪlt/", "zh": "v. 倾斜，翘起；俯仰（摄影机）；以言词或文字抨击 n. 倾斜；（意欲赢得某物或战胜某人的）企" },
  { "en": "ensue", "phonetic": "/ɪnˈsuː/", "zh": "v. 接着发生，因而发生；追求" },
  { "en": "supervise", "phonetic": "/ˈsuːpərvaɪz/", "zh": "v. 监督；管理；指导；主管；照看" },
  { "en": "recycle", "phonetic": "/ˌriːˈsaɪkl/", "zh": "v. 回收利用；使再循环；重新使用 n. 回收利用，循环使用" },
  { "en": "retort", "phonetic": "/rɪˈtɔːrt/", "zh": "v. 反驳，回嘴；蒸馏；在曲颈瓶里加热；（对侮辱或伤害）进行报复 n. 反驳，顶嘴；曲颈瓶，" },
  { "en": "foster", "phonetic": "/ˈfɑːstər/", "zh": "v. 促进；抚育（他人子女一段时间）；收养；把（孩子）交托给养父母 adj. 代养的，寄养的" },
  { "en": "rig", "phonetic": "/rɪɡ/", "zh": "v. 操纵；装配；装扮；装上索具；为……提供服装 n. 装备；钻探设备；服装； 帆装；重型铰接" },
  { "en": "peel", "phonetic": "/piːl/", "zh": "v. 剥，剥落；削；（槌球中）击（他人的球）穿过铁环门 n. 皮" },
  { "en": "mourn", "phonetic": "/mɔːrn/", "zh": "v. 哀悼；忧伤；服丧" },
  { "en": "overflow", "phonetic": "/ˌoʊvərˈfloʊ/", "zh": "v. （尤指液体）溢出；（容器）满得溢出；挤满人了；淹没（某一表面或地区）；过度延" },
  { "en": "pave", "phonetic": "/peɪv/", "zh": "v. （用石板或砖）铺（路），铺砌，铺设；为某事物铺平道路，创造条件" },
  { "en": "tug", "phonetic": "/tʌɡ/", "zh": "v. （用力地）拉，拖；（迅速地）穿衣服；较量；用拖船拖；竞争；努力做 n. 拖船；拖曳；苦干；" },
  { "en": "sparkle", "phonetic": "/ˈspɑːrkl/", "zh": "v. （使）闪耀；（使）发光；（酒类饮料）发泡；活跃，生机勃勃；活泼机智 n. 闪耀；" },
  { "en": "affiliate", "phonetic": "/əˈfɪlieɪt/", "zh": "v. （使）附属，隶属；加入，加盟，并入；接纳；紧密联系 n. 分支机构；子公司；分" },
  { "en": "tangle", "phonetic": "/ˈtæŋɡl/", "zh": "v. （使）缠结在一起；（使）乱成一团；处于混乱状态；（和……）争吵；打架 n. 缠结；混乱，" },
  { "en": "cripple", "phonetic": "/ˈkrɪpl/", "zh": "v. （使）跛；（使）残废；削弱；严重毁坏（机器）；给……造成严重问题 n. 古，冒犯跛子，" },
  { "en": "notwithstanding", "phonetic": "/ˌnɒtwɪθˈstændɪŋ/", "zh": "prep. 尽管，虽然 adv. 尽管，仍然 conj. 虽然，尽管" },
  { "en": "versus", "phonetic": "/ˈvɜːrsəs/", "zh": "prep. 对，对抗；与……相对，与……相比" },
  { "en": "brace", "phonetic": "/breɪs/", "zh": "n.支柱,带子,振作精神 vt.支住,撑牢,振作起来,奋起 adj.曲柄的 v.支持" },
  { "en": "swamp", "phonetic": "/swɑːmp/", "zh": "n.沼泽,湿地,煤层聚水 v.陷入沼泽,淹没,覆没" },
  { "en": "manifest", "phonetic": "/ˈmænɪfest/", "zh": "n.载货单,旅客名单 adj.显然的,明白的 vi.出现 vt.表明,证明" },
  { "en": "haul", "phonetic": "/hɔːl/", "zh": "n.用力拖拉,拖,拉,捕获物,努力得到的结果,(尤指)一网捕获的鱼量,拖运距离 vi.拖,拉,改变方向,改变" },
  { "en": "poll", "phonetic": "/poʊl/", "zh": "n.选举之投票,民意测验 v.投票,获得选票,选举中获得" },
  { "en": "slaughter", "phonetic": "/ˈslɔːtər/", "zh": "n.屠宰,残杀,屠杀 v.屠宰,残杀,屠杀" },
  { "en": "queer", "phonetic": "/kwɪr/", "zh": "n.同性恋者 adj.奇怪的,可疑的,不舒服的 vt.搞糟 n.同性恋者" },
  { "en": "vent", "phonetic": "/vent/", "zh": "n.通风孔,出烟孔,出口,(感情等的)发泄 v.放出,排出,发泄" },
  { "en": "slack", "phonetic": "/slæk/", "zh": "n.松弛,静止,淡季,闲散,家常裤 adj.松弛的,不流畅的,疏忽的,软弱的,漏水的,呆滞的,懒散的" },
  { "en": "upgrade", "phonetic": "/ˈʌpɡreɪd/", "zh": "n.升级,上升,上坡 adv.往上 vt.使升级,提升,改良品种" },
  { "en": "scar", "phonetic": "/skɑːr/", "zh": "n.伤痕,疤痕 v.结疤,使留下伤痕,创伤" },
  { "en": "offset", "phonetic": "/ˈɔːfset/", "zh": "n.偏移量,抵销,弥补,分支,平版印刷,胶印 vt.弥补,抵销,用平版印刷 vi.偏移,形成分支" },
  { "en": "transit", "phonetic": "/ˈtrænzɪt/", "zh": "n.经过,通行,搬运,运输,运输线,转变 vt.横越,通过,经过 vi.通过 n.[天] 中天,经纬仪" },
  { "en": "splash", "phonetic": "/splæʃ/", "zh": "n.溅,飞溅,斑点 v.溅,泼,溅湿" },
  { "en": "stall", "phonetic": "/stɔːl/", "zh": "n.货摊,畜栏,厩,出售摊 v.(使)停转,(使)停止,迟延" },
  { "en": "traverse", "phonetic": "/'trævɜːs/", "zh": "n.横贯,横断,横木,障碍,否认,反驳,(建筑)通廊 vt.横过,穿过,经过,在...来回移动,反对,详细" },
  { "en": "sponge", "phonetic": "/spʌndʒ/", "zh": "n.海绵,海绵体,海绵状物,(外科用的)棉球,纱布 v.用海绵等冼涤、揩拭、擦拭或清除,用海绵吸" },
  { "en": "tackle", "phonetic": "/ˈtækl/", "zh": "n.工具,复滑车,滑车,用具,装备,扭倒 vt.固定,应付(难事等),处理,解决,抓住 vi.捉住,扭住,扭倒" },
  { "en": "tuck", "phonetic": "/tʌk/", "zh": "n.缝摺,活力,鼓声,船尾突出部下方,食物(尤指点心、蛋糕) vt.打摺,卷起,挤进,塞,使隐藏 vi.折成摺子," },
  { "en": "landscape", "phonetic": "/ˈlændskeɪp/", "zh": "n.风景,山水画,地形,前景 v.美化" },
  { "en": "orient", "phonetic": "/ˈɔːrient/", "zh": "n.东方,东方诸国(指地中海以东各国) adj.东方的,上升的,灿烂的 vi.适应形势,向东 vt.使朝东," },
  { "en": "tick", "phonetic": "/tɪk/", "zh": "n.滴答声,记号,勾号,扁虱 v.滴答地响,标以记号,作滴答声" },
  { "en": "virgin", "phonetic": "/ˈvɜːrdʒɪn/", "zh": "n.处女,(晚近用法)处男 adj.处女的,童贞的,纯洁的,洁白无瑕疵的,未被玷污的,原始的,处" },
  { "en": "gear", "phonetic": "/ɡɪr/", "zh": "n.齿轮,传动装置 v.调整,(使)适合,换档" },
  { "en": "precipitate", "phonetic": "/prɪˈsɪpɪteɪt/", "zh": "n.沉淀物 vt.猛抛,使陷入,促成,使沉淀 vi.猛地落下 adj.突如其来的,陡然下降" },
  { "en": "foil", "phonetic": "/fɔɪl/", "zh": "n.箔,金属薄片,[建]叶形片,烘托,衬托 vt.衬托,阻止,挡开,挫败,贴箔于" },
  { "en": "token", "phonetic": "/ˈtoʊkən/", "zh": "n.表示,向征,记号,代币 adj.象征的,表意的" },
  { "en": "flutter", "phonetic": "/ˈflʌtər/", "zh": "n.摆动,鼓翼,烦扰 vi.鼓翼,飘动,悸动,乱跳,烦扰 vt.拍(翅),使焦急" },
  { "en": "sin", "phonetic": "/sɪn/", "zh": "n. 罪恶；罪孽；过失 vi. 犯罪；犯过失 vt. 犯罪" },
  { "en": "lease", "phonetic": "/liːs/", "zh": "n. 租约；租期；租赁物；租赁权 vt. 出租；租得 vi. 出租" },
  { "en": "synthesis", "phonetic": "/ˈsɪnθəsɪs/", "zh": "n. 综合，[化学] 合成；综合体" },
  { "en": "ego", "phonetic": "/ˈiːɡoʊ/", "zh": "n. 自我；自负；自我意识" },
  { "en": "suicide", "phonetic": "/ˈsuːɪsaɪd/", "zh": "n. 自杀；自杀行为；自杀者 adj. 自杀的 vt. 自杀 vi. 自杀" },
  { "en": "qualification", "phonetic": "/ˌkwɑːlɪfɪˈkeɪʃn/", "zh": "n. 资格；条件；限制；赋予资格" },
  { "en": "membership", "phonetic": "/ˈmembərʃɪp/", "zh": "n. 资格；成员资格；会员身份" },
  { "en": "asset", "phonetic": "/ˈæset/", "zh": "n. 资产；优点；有用的东西；有利条件；财产；有价值的人或物" },
  { "en": "quest", "phonetic": "/kwest/", "zh": "n. 追求；寻找；任务（游戏术语） vi. 追求；寻找 vt. 探索" },
  { "en": "pursuit", "phonetic": "/pərˈsuːt/", "zh": "n. 追赶，追求；职业，工作" },
  { "en": "ornament", "phonetic": "/ˈɔːrnəmənt/", "zh": "n. 装饰；[建][服装] 装饰物；教堂用品 vt. 装饰，修饰" },
  { "en": "shipment", "phonetic": "/ˈʃɪpmənt/", "zh": "n. 装货 n. 装载的货物 n. 出货量" },
  { "en": "expertise", "phonetic": "/ˌekspɜːrˈtiːz/", "zh": "n. 专门知识；专门技术；专家的意见" },
  { "en": "patent", "phonetic": "/ˈpeɪt(ə)nt/", "zh": "n. 专利权；专利证；专利品 adj. 专利的；特许生产或销售的；显著的；公开的；（脉管" },
  { "en": "theme", "phonetic": "/θiːm/", "zh": "n. 主题；主旋律；题目 adj. 以奇想主题布置的" },
  { "en": "wrinkle", "phonetic": "/ˈrɪŋkl/", "zh": "n. 皱纹 vi. 起皱 vt. 使起皱纹" },
  { "en": "therapy", "phonetic": "/ˈθerəpi/", "zh": "n. 治疗，疗法" },
  { "en": "texture", "phonetic": "/ˈtekstʃər/", "zh": "n. 质地；纹理；结构；本质，实质 vt. 使具有浮凸纹理；使质地不平" },
  { "en": "sanction", "phonetic": "/ˈsæŋkʃn/", "zh": "n. 制裁，处罚；认可；支持 vt. 制裁，处罚；批准；鼓励" },
  { "en": "volunteer", "phonetic": "/ˌvɑːlənˈtɪr/", "zh": "n. 志愿者；志愿兵 adj. 志愿的 vi. 自愿 vt. 自愿" },
  { "en": "vegetation", "phonetic": "/ˌvedʒəˈteɪʃn/", "zh": "n. 植被；植物，草木；呆板单调的生活" },
  { "en": "intuition", "phonetic": "/ˌɪntuˈɪʃn/", "zh": "n. 直觉；直觉力；直觉的知识" },
  { "en": "regime", "phonetic": "/reɪˈʒiːm/", "zh": "n. 政权，政体；社会制度；管理体制" },
  { "en": "controversy", "phonetic": "/ˈkɑːntrəvɜːrsi/", "zh": "n. 争论；论战；辩论" },
  { "en": "pearl", "phonetic": "/pɜːrl/", "zh": "n. 珍珠；珍珠色；杰出者；珍品 adj. 镶珍珠的；珍珠状的 vi. 采珍珠；成珍珠状 vt. 使成" },
  { "en": "stitch", "phonetic": "/stɪtʃ/", "zh": "n. 针脚，线迹；一针 vt. 缝，缝合 vi. 缝，缝合" },
  { "en": "marsh", "phonetic": "/mɑːrʃ/", "zh": "n. 沼泽；湿地 adj. 沼泽的；生长在沼泽地的" },
  { "en": "warfare", "phonetic": "/ˈwɔːrfer/", "zh": "n. 战争；冲突" },
  { "en": "presentation", "phonetic": "/ˌpriːzenˈteɪʃn/", "zh": "n. 展示；描述，陈述；介绍；赠送" },
  { "en": "liability", "phonetic": "/ˌlaɪəˈbɪləti/", "zh": "n. 责任；债务；倾向；可能性；不利因素" },
  { "en": "reproach", "phonetic": "/rɪˈproʊtʃ/", "zh": "n. 责备；耻辱 vt. 责备；申斥" },
  { "en": "prototype", "phonetic": "/ˈproʊtətaɪp/", "zh": "n. 原型；样本；标准，模范；全真模型；[电]原型滤波网络 vt. 制作原型" },
  { "en": "ingredient", "phonetic": "/ɪnˈɡriːdiənt/", "zh": "n. 原料；要素；组成部分 adj. 构成组成部分的" },
  { "en": "marshal", "phonetic": "/ˈmɑːrʃl/", "zh": "n. 元帅；司仪 vt. 整理；引领；编列 vi. 排列" },
  { "en": "reservation", "phonetic": "/ˌrezərˈveɪʃn/", "zh": "n. 预约，预订；保留" },
  { "en": "blunder", "phonetic": "/ˈblʌndər/", "zh": "n. 愚蠢（或粗心）的错误，大错 v. 犯大错，笨嘴笨舌；跌跌撞撞地走；误入（某地）" },
  { "en": "recreation", "phonetic": "/ˌriːkriˈeɪʃn/", "zh": "n. 娱乐；消遣；休养" },
  { "en": "pastime", "phonetic": "/ˈpæstaɪm/", "zh": "n. 娱乐，消遣" },
  { "en": "yacht", "phonetic": "/jɑːt/", "zh": "n. 游艇，快艇；轻舟 v. 乘游艇，驾游艇；驾帆船比赛" },
  { "en": "grease", "phonetic": "/ɡriːs/", "zh": "n. 油脂；润滑油；（非正式）贿赂 v. 涂脂于；给……加润滑油；（非正式）向某人行贿" },
  { "en": "superiority", "phonetic": "/suːˌpɪriˈɔːrəti/", "zh": "n. 优越，优势；优越性" },
  { "en": "priority", "phonetic": "/praɪˈɔːrəti/", "zh": "n. 优先；优先权；[数] 优先次序；优先考虑的事" },
  { "en": "privacy", "phonetic": "/ˈpraɪvəsi/", "zh": "n. 隐私；秘密；隐居；隐居处" },
  { "en": "intrigue", "phonetic": "/ɪnˈtriːɡ/", "zh": "n. 阴谋；诡计；复杂的事；私通 vt. 用诡计取得；激起...的兴趣 vi. 私通；密谋" },
  { "en": "casualty", "phonetic": "/ˈkæʒuəlti/", "zh": "n. 意外事故；伤亡人员；急诊室" },
  { "en": "intent", "phonetic": "/ɪnˈtent/", "zh": "n. 意图；目的；含义 adj. 专心的；急切的；坚决的" },
  { "en": "ideology", "phonetic": "/ˌaɪdiˈɑːlədʒi/", "zh": "n. 意识形态；思想意识；观念学" },
  { "en": "curb", "phonetic": "/kɜːrb/", "zh": "n. 抑制；路边；勒马绳 vt. 控制；勒住" },
  { "en": "obligation", "phonetic": "/ˌɑːblɪˈɡeɪʃn/", "zh": "n. 义务；职责；债务" },
  { "en": "heritage", "phonetic": "/ˈherɪtɪdʒ/", "zh": "n. 遗产；传统；继承物；继承权" },
  { "en": "ritual", "phonetic": "/ˈrɪtʃuəl/", "zh": "n. 仪式；惯例；礼制 adj. 仪式的；例行的；礼节性的" },
  { "en": "garment", "phonetic": "/ˈɡɑːrmənt/", "zh": "n. 衣服，服装；外表，外观 vt. 给…穿衣服" },
  { "en": "consensus", "phonetic": "/kənˈsensəs/", "zh": "n. 一致；舆论；合意" },
  { "en": "batch", "phonetic": "/bætʃ/", "zh": "n. 一批；一炉；一次所制之量 vt. 分批处理" },
  { "en": "prescription", "phonetic": "/prɪˈskrɪpʃn/", "zh": "n. 药方；指示；惯例 adj. 凭处方方可购买的" },
  { "en": "patrol", "phonetic": "/pəˈtroʊl/", "zh": "n. 巡逻；巡逻队；侦察队 vt. 巡逻；巡查 vi. 巡逻；巡查" },
  { "en": "medal", "phonetic": "/ˈmedl/", "zh": "n. 勋章，奖章；纪念章" },
  { "en": "vein", "phonetic": "/veɪn/", "zh": "n. 血管；叶脉；[地质] 岩脉；纹理；翅脉；性情 vt. 使成脉络；像脉络般分布于" },
  { "en": "tuition", "phonetic": "/tuˈɪʃn/", "zh": "n. 学费；讲授" },
  { "en": "melody", "phonetic": "/ˈmelədi/", "zh": "n. 旋律；歌曲；美妙的音乐" },
  { "en": "suspension", "phonetic": "/səˈspenʃn/", "zh": "n. 悬浮；暂停；停职" },
  { "en": "propaganda", "phonetic": "/ˌprɑːpəˈɡændə/", "zh": "n. 宣传；传道总会" },
  { "en": "publicity", "phonetic": "/pʌbˈlɪsəti/", "zh": "n. 宣传，宣扬；公开；广告；注意" },
  { "en": "narrative", "phonetic": "/ˈnærətɪv/", "zh": "n. 叙述；故事；讲述 adj. 叙事的，叙述的；叙事体的" },
  { "en": "lounge", "phonetic": "/laʊndʒ/", "zh": "n. 休息室；闲逛；躺椅；（英）酒吧间 vi. 闲逛；懒洋洋地躺卧；闲混 vt. 虚度光阴" },
  { "en": "surge", "phonetic": "/sɜːrdʒ/", "zh": "n. 汹涌；大浪，波涛；汹涌澎湃；巨涌 v. 汹涌；起大浪，蜂拥而来" },
  { "en": "survival", "phonetic": "/sərˈvaɪvl/", "zh": "n. 幸存，残存；幸存者，残存物" },
  { "en": "reliance", "phonetic": "/rɪˈlaɪəns/", "zh": "n. 信赖；信心；受信赖的人或物" },
  { "en": "journalist", "phonetic": "/ˈdʒɜːrnəlɪst/", "zh": "n. 新闻工作者；报人；记日志者" },
  { "en": "novelty", "phonetic": "/ˈnɑːvlti/", "zh": "n. 新奇；新奇的事物；新颖小巧而廉价的物品" },
  { "en": "wedge", "phonetic": "/wedʒ/", "zh": "n. 楔子；楔形物；不和 v. 楔入；挤进；楔住" },
  { "en": "leaflet", "phonetic": "/ˈliːflət/", "zh": "n. 小叶；传单" },
  { "en": "gossip", "phonetic": "/ˈɡɑːsɪp/", "zh": "n. 小道传闻；随笔；爱说长道短的人 vi. 闲聊；传播流言蜚语" },
  { "en": "snack", "phonetic": "/snæk/", "zh": "n. 小吃，点心；快餐；易办到的事，小事一桩 v. 吃点心（或快餐、小吃）" },
  { "en": "pamphlet", "phonetic": "/ˈpæmflət/", "zh": "n. 小册子" },
  { "en": "ivory", "phonetic": "/ˈaɪvəri/", "zh": "n. 象牙；乳白色；长牙 adj. 乳白色的；象牙制的" },
  { "en": "scrutiny", "phonetic": "/ˈskruːtəni/", "zh": "n. 详细审查；监视；细看；选票复查" },
  { "en": "perfume", "phonetic": "/pərˈfjuːm/", "zh": "n. 香水；香味 vt. 洒香水于…；使…带香味 vi. 散发香气" },
  { "en": "resemblance", "phonetic": "/rɪˈzembləns/", "zh": "n. 相似；相似之处；相似物；肖像" },
  { "en": "prophet", "phonetic": "/ˈprɑːfɪt/", "zh": "n. 先知；预言者；提倡者" },
  { "en": "raid", "phonetic": "/reɪd/", "zh": "n. 袭击；突袭；搜捕；抢劫 vi. 突袭 vt. 袭击，突袭" },
  { "en": "questionnaire", "phonetic": "/ˌkwestʃəˈner/", "zh": "n. 问卷；调查表" },
  { "en": "plague", "phonetic": "/pleɪɡ/", "zh": "n. 瘟疫，鼠疫；灾祸，天灾；麻烦事，讨厌的人；愿上天降灾难于……（用于诅咒） v. 使折" },
  { "en": "slot", "phonetic": "/slɑːt/", "zh": "n. 位置；狭槽；水沟；硬币投币口 vt. 跟踪；开槽于" },
  { "en": "latitude", "phonetic": "/ˈlætɪtuːd/", "zh": "n. 纬度；界限；活动范围" },
  { "en": "majesty", "phonetic": "/ˈmædʒəsti/", "zh": "n. 威严；最高权威，王权；雄伟；权威" },
  { "en": "menace", "phonetic": "/ˈmenəs/", "zh": "n. 威胁；恐吓 vi. 恐吓；进行威胁 vt. 威胁；恐吓" },
  { "en": "prestige", "phonetic": "/preˈstiːʒ/", "zh": "n. 威望，声望；声誉 adj. 令人敬仰的；受尊重的；贵重的" },
  { "en": "web", "phonetic": "/web/", "zh": "n. 网；卷筒纸；蹼；织物；圈套 vt. 用网缠住；使中圈套 vi. 形成网" },
  { "en": "integrity", "phonetic": "/ɪnˈteɡrəti/", "zh": "n. 完整；正直；诚实；廉正" },
  { "en": "perfection", "phonetic": "/pərˈfekʃn/", "zh": "n. 完善；完美" },
  { "en": "layman", "phonetic": "/ˈleɪmən/", "zh": "n. 外行；门外汉；俗人；一般信徒" },
  { "en": "surgeon", "phonetic": "/ˈsɜːrdʒən/", "zh": "n. 外科医生" },
  { "en": "watt", "phonetic": "/wɑːt/", "zh": "n. 瓦特" },
  { "en": "pension", "phonetic": "/'penʃən/", "zh": "n. 退休金，抚恤金；津贴；膳宿费 vt. 发给养老金或抚恤金" },
  { "en": "solidarity", "phonetic": "/ˌsɑːlɪˈdærəti/", "zh": "n. 团结，团结一致" },
  { "en": "misery", "phonetic": "/ˈmɪzəri/", "zh": "n. 痛苦，悲惨；不幸；苦恼；穷困" },
  { "en": "statistics", "phonetic": "/stəˈtɪstɪks/", "zh": "n. 统计；统计学；[统计] 统计资料；统计数字" },
  { "en": "peer", "phonetic": "/pɪr/", "zh": "n. 同等地位的人，同龄人；贵族 v. 凝视，盯着看；隐现；看见；匹配" },
  { "en": "paradise", "phonetic": "/ˈpærədaɪs/", "zh": "n. 天堂至福境地" },
  { "en": "cue", "phonetic": "/kjuː/", "zh": "n. 提示，暗示；线索 vt. 给…暗示" },
  { "en": "trait", "phonetic": "/treɪt/", "zh": "n. 特性，特点；品质；少许" },
  { "en": "symposium", "phonetic": "/sɪmˈpoʊziəm/", "zh": "n. 讨论会，座谈会；专题论文集；酒宴，宴会" },
  { "en": "seminar", "phonetic": "/ˈsemɪnɑːr/", "zh": "n. 讨论会，研讨班" },
  { "en": "probe", "phonetic": "/proʊb/", "zh": "n. 探针；调查 vi. 调查；探测 vt. 探查；用探针探测" },
  { "en": "locality", "phonetic": "/loʊˈkæləti/", "zh": "n. 所在；位置；地点" },
  { "en": "scrap", "phonetic": "/skræp/", "zh": "n. 碎片；残余物；打架；少量 vt. 废弃；使解体；拆毁 adj. 废弃的；零碎的 vi. 吵架" },
  { "en": "tempo", "phonetic": "/ˈtempoʊ/", "zh": "n. 速度，发展速度；拍子" },
  { "en": "recession", "phonetic": "/rɪˈseʃn/", "zh": "n. 衰退；不景气；后退；凹处" },
  { "en": "shaft", "phonetic": "/ʃæft/", "zh": "n. 竖井；通风井；（电梯的）升降机井；杆，柄 vt. 欺骗；苛待" },
  { "en": "tract", "phonetic": "/trækt/", "zh": "n. 束；大片土地，地带；小册子" },
  { "en": "oath", "phonetic": "/oʊθ/", "zh": "n. 誓言，誓约；诅咒，咒骂" },
  { "en": "momentum", "phonetic": "/moʊˈmentəm/", "zh": "n. 势头；[物] 动量；动力；冲力" },
  { "en": "recipe", "phonetic": "/ˈresəpi/", "zh": "n. 食谱；[临床] 处方；秘诀；烹饪法" },
  { "en": "entity", "phonetic": "/ˈentəti/", "zh": "n. 实体；存在" },
  { "en": "quartz", "phonetic": "/kwɔːrts/", "zh": "n. 石英" },
  { "en": "plaster", "phonetic": "/ˈplæstər/", "zh": "n. 石膏；灰泥；膏药 vt. 减轻；粘贴；涂以灰泥；敷以膏药；使平服" },
  { "en": "verse", "phonetic": "/vɜːrs/", "zh": "n. 诗，诗篇；韵文；诗节 vi. 作诗 vt. 使熟练，使精通" },
  { "en": "unemployment", "phonetic": "/ˌʌnɪmˈplɔɪmənt/", "zh": "n. 失业；失业率；失业人数" },
  { "en": "remnant", "phonetic": "/ˈremnənt/", "zh": "n. 剩余 adj. 剩余的" },
  { "en": "surplus", "phonetic": "/ˈsɜːrplʌs/", "zh": "n. 剩余；[贸易] 顺差；盈余；过剩 adj. 剩余的；过剩的" },
  { "en": "saint", "phonetic": "/seɪnt/", "zh": "n. 圣人；圣徒；道德崇高的人 adj. 神圣的 vt. 成为圣徒" },
  { "en": "productivity", "phonetic": "/ˌproʊdʌkˈtɪvəti/", "zh": "n. 生产力；生产率；生产能力" },
  { "en": "myth", "phonetic": "/mɪθ/", "zh": "n. 神话；虚构的人，虚构的事" },
  { "en": "sociology", "phonetic": "/ˌsoʊsiˈɑːlədʒi/", "zh": "n. 社会学；群体生态学" },
  { "en": "trifle", "phonetic": "/ˈtraɪfl/", "zh": "n. 少量；琐事；不值钱的东西；屈莱弗甜食 v. 轻浮地说（或做）；虚度，浪费；轻视" },
  { "en": "mall", "phonetic": "/mɔːl/", "zh": "n. 商场，购物广场；步行商业区；步行道；铁圈球球场" },
  { "en": "prose", "phonetic": "/proʊz/", "zh": "n. 散文；单调 adj. 散文的；平凡的；乏味的 vi. 写散文；乏味地讲话 vt. 把…写成散文" },
  { "en": "software", "phonetic": "/ˈsɔːftwer/", "zh": "n. 软件" },
  { "en": "hose", "phonetic": "/hoʊz/", "zh": "n. 软管；长筒袜；男性穿的紧身裤 vt. 用软管浇水；痛打" },
  { "en": "threshold", "phonetic": "/ˈθreʃhoʊld/", "zh": "n. 入口；门槛；开始；极限；临界值" },
  { "en": "recipient", "phonetic": "/rɪˈsɪpiənt/", "zh": "n. 容器，接受者；容纳者 adj. 容易接受的；容纳的" },
  { "en": "perception", "phonetic": "/pərˈsepʃn/", "zh": "n. 认识能力；知觉，感觉；洞察力；看法；获取" },
  { "en": "concession", "phonetic": "/kənˈseʃn/", "zh": "n. 让步；特许（权）；承认；退位" },
  { "en": "repertoire", "phonetic": "/ˈrepərtwɑːr/", "zh": "n. 全部节目；计算机指令系统；（美）某人或机器的全部技能" },
  { "en": "racket", "phonetic": "/ˈrækɪt/", "zh": "n. 球拍；吵闹，喧闹 vt. 过着花天酒地的生活 vi. 过着花天酒地的生活" },
  { "en": "petition", "phonetic": "/pəˈtɪʃn/", "zh": "n. 请愿；请愿书；祈求；[法] 诉状 vi. 请愿；请求 vt. 请愿；请求；恳求" },
  { "en": "contempt", "phonetic": "/kənˈtempt/", "zh": "n. 轻视，蔑视；耻辱" },
  { "en": "scorn", "phonetic": "/skɔːrn/", "zh": "n. 轻蔑；嘲笑；藐视的对象 v. 轻蔑；藐视；不屑做" },
  { "en": "erosion", "phonetic": "/ɪˈroʊʒn/", "zh": "n. 侵蚀，腐蚀" },
  { "en": "wallet", "phonetic": "/ˈwɑːlɪt/", "zh": "n. 钱包，皮夹" },
  { "en": "premise", "phonetic": "/ˈpremɪs/", "zh": "n. 前提，假定；（常复数）商店、餐馆、公司等使用的房屋及土地；（常复数）上诉各项" },
  { "en": "v.", "phonetic": "", "zh": "以……为前提；引出，预先提出；说明" },
  { "en": "predecessor", "phonetic": "/ˈpredəsesər/", "zh": "n. 前任，前辈" },
  { "en": "motel", "phonetic": "/moʊˈtel/", "zh": "n. 汽车旅馆" },
  { "en": "temperament", "phonetic": "/ˈtemprəmənt/", "zh": "n. 气质，性情，性格；急躁" },
  { "en": "scent", "phonetic": "/sent/", "zh": "n. 气味；嗅觉；痕迹；察觉能力 vt. 闻到；发觉；使充满…的气味；循着遗臭追踪 vi. 发出…" },
  { "en": "odor", "phonetic": "/ˈoʊdər/", "zh": "n. 气味；名声" },
  { "en": "revelation", "phonetic": "/ˌrevəˈleɪʃn/", "zh": "n. 启示；揭露；出乎意料的事；被揭露的真相" },
  { "en": "entrepreneur", "phonetic": "/ˌɑːntrəprəˈnɜːr/", "zh": "n. 企业家；承包人；主办者" },
  { "en": "prayer", "phonetic": "/prer/", "zh": "n. 祈祷，祷告；恳求；祈祷文" },
  { "en": "fraud", "phonetic": "/frɔːd/", "zh": "n. 欺骗；骗子；诡计" },
  { "en": "pope", "phonetic": "/poʊp/", "zh": "n. 蒲伯（英国诗人）；罗马教皇" },
  { "en": "rupture", "phonetic": "/ˈrʌptʃər/", "zh": "n. 破裂；决裂；疝气 vi. 破裂；发疝气 vt. 使破裂；断绝；发生疝" },
  { "en": "fracture", "phonetic": "/ˈfræktʃər/", "zh": "n. 破裂，断裂；[外科] 骨折 vi. 破裂；折断 vt. 使破裂" },
  { "en": "commentary", "phonetic": "/ˈkɑːmənteri/", "zh": "n. 评论；注释；评注；说明" },
  { "en": "appraisal", "phonetic": "/əˈpreɪzl/", "zh": "n. 评价；估价（尤指估价财产，以便征税）；估计" },
  { "en": "terrace", "phonetic": "/ˈterəs/", "zh": "n. 平台；梯田；阳台 vt. 使成梯田，使成阶地；使有平台屋顶 vi. 成阶地；成梯田；筑成坛" },
  { "en": "slum", "phonetic": "/slʌm/", "zh": "n. 贫民窟；（不宜居住的）房屋；脏乱的地方 v. （为猎奇或救济）去贫民窟；将就适应，过" },
  { "en": "inflation", "phonetic": "/ɪnˈfleɪʃn/", "zh": "n. 膨胀；通货膨胀；夸张；自命不凡" },
  { "en": "configuration", "phonetic": "/kənˌfɪɡjəˈreɪʃn/", "zh": "n. 配置；结构；外形" },
  { "en": "spouse", "phonetic": "/spaʊs,spaʊz/", "zh": "n. 配偶 vt. 和…结婚" },
  { "en": "amends", "phonetic": "/əˈmendz/", "zh": "n. 赔偿；赔罪 v. 修订（amend的第三人称单数）；改进" },
  { "en": "escort", "phonetic": "/ˈeskɔːrt/", "zh": "n. 陪同；护航舰；护卫队；护送者 vt. 护送；陪同；为…护航" },
  { "en": "foam", "phonetic": "/foʊm/", "zh": "n. 泡沫；水沫；灭火泡沫 vi. 起泡沫；吐白沫；起着泡沫流动 vt. 使起泡沫；使成泡沫状物" },
  { "en": "rebellion", "phonetic": "/rɪˈbeljən/", "zh": "n. 叛乱；反抗；谋反；不服从" },
  { "en": "flap", "phonetic": "/flæp/", "zh": "n. 拍打，拍打声；神经紧张；（飞机的）襟翼；风门，挡板；[医]皮瓣 vi. 拍动；神经紧张；鼓翼" },
  { "en": "nickel", "phonetic": "/ˈnɪkl/", "zh": "n. 镍；镍币；五分镍币 vt. 镀镍于" },
  { "en": "youngster", "phonetic": "/ˈjʌŋstər/", "zh": "n. 年轻人；少年" },
  { "en": "competence", "phonetic": "/ˈkɑːmpɪtəns/", "zh": "n. 能力，胜任；权限；作证能力；足以过舒适生活的收入" },
  { "en": "refugee", "phonetic": "/ˌrefjuˈdʒiː/", "zh": "n. 难民，避难者；流亡者，逃亡者" },
  { "en": "priest", "phonetic": "/priːst/", "zh": "n. 牧师；神父；教士 vt. 使成为神职人员；任命…为祭司" },
  { "en": "goal", "phonetic": "/ɡoʊl/", "zh": "n. 目标；球门，得分数；终点 vi. 攻门，射门得分" },
  { "en": "timber", "phonetic": "/ˈtɪmbər/", "zh": "n. 木材；木料" },
  { "en": "imitation", "phonetic": "/ˌɪmɪˈteɪʃn/", "zh": "n. 模仿，仿造；仿制品 adj. 人造的，仿制的" },
  { "en": "proposition", "phonetic": "/ˌprɑːpəˈzɪʃn/", "zh": "n. 命题；提议；主题；议题 vt. 向……提议；向……求欢" },
  { "en": "veil", "phonetic": "/veɪl/", "zh": "n. 面纱；面罩；遮蔽物；托词 vt. 遮蔽；掩饰；以面纱遮掩；用帷幕分隔 vi. 蒙上面纱；出现轻" },
  { "en": "facet", "phonetic": "/ˈfæsɪt/", "zh": "n. 面；方面；小平面 vt. 在…上琢面" },
  { "en": "porch", "phonetic": "/pɔːrtʃ/", "zh": "n. 门廊；走廊" },
  { "en": "media", "phonetic": "/ˈmiːdiə/", "zh": "n. 媒体；媒质（medium的复数）；血管中层；浊塞音；中脉" },
  { "en": "attorney", "phonetic": "/əˈtɜːrni/", "zh": "n. 律师；代理人；检察官" },
  { "en": "thesis", "phonetic": "/ˈθiːsɪs/", "zh": "n. 论文；论点" },
  { "en": "ethics", "phonetic": "/ˈeθɪks/", "zh": "n. 伦理学；伦理观；道德标准" },
  { "en": "staircase", "phonetic": "/ˈsterkeɪs/", "zh": "n. 楼梯" },
  { "en": "monopoly", "phonetic": "/məˈnɑːpəli/", "zh": "n. 垄断；垄断者；专卖权" },
  { "en": "exile", "phonetic": "/ˈeksaɪl,ˈeɡzaɪl/", "zh": "n. 流放，充军；放逐，被放逐者；流犯 vt. 放逐，流放；使背井离乡" },
  { "en": "retail", "phonetic": "/ˈriːteɪl; rɪˈteɪl/", "zh": "n. 零售 v. 零售，（以某价格）零售；详述；散播（私密消息） adv. 以零售方式 adj." },
  { "en": "vicinity", "phonetic": "/vəˈsɪnəti/", "zh": "n. 邻近，附近；近处" },
  { "en": "prey", "phonetic": "/preɪ/", "zh": "n. 猎物；受害者，牺牲品；（情绪易受伤的）脆弱的人；掠夺品 v. 捕食；伤害；折磨，困扰" },
  { "en": "junction", "phonetic": "/ˈdʒʌŋkʃn/", "zh": "n. 连接，接合；交叉点；接合点" },
  { "en": "stereo", "phonetic": "/ˈsterioʊ/", "zh": "n. 立体声；立体声系统 adj. 立体的；立体声的；立体感觉的" },
  { "en": "legislation", "phonetic": "/ˌledʒɪsˈleɪʃn/", "zh": "n. 立法；法律" },
  { "en": "justification", "phonetic": "/ˌdʒʌstɪfɪˈkeɪʃn/", "zh": "n. 理由；辩护；认为有理，认为正当；释罪" },
  { "en": "tribute", "phonetic": "/ˈtrɪbjuːt/", "zh": "n. 礼物；[税收] 贡物；颂词；（尤指对死者的）致敬，悼念，吊唁礼物" },
  { "en": "courtesy", "phonetic": "/ˈkɜːrtəsi/", "zh": "n. 礼貌；好意；恩惠 adj. 殷勤的；被承认的；出于礼节的" },
  { "en": "optimism", "phonetic": "/ˈɑːptɪmɪzəm/", "zh": "n. 乐观；乐观主义" },
  { "en": "litter", "phonetic": "/ˈlɪtər/", "zh": "n. 垃圾；轿，担架；一窝（动物的幼崽）；凌乱 vt. 乱丢；给…垫褥草；把…弄得乱七八糟 vi. 产" },
  { "en": "dilemma", "phonetic": "/dɪˈlemə/", "zh": "n. 困境；进退两难；两刀论法" },
  { "en": "shutter", "phonetic": "/ˈʃʌtər/", "zh": "n. 快门；百叶窗；关闭物；遮板 vt. 为…装百叶窗；以百叶窗遮闭" },
  { "en": "quart", "phonetic": "/kwɔːrt/", "zh": "n. 夸脱（容量单位）；一夸脱的容器" },
  { "en": "panic", "phonetic": "/ˈpænɪk/", "zh": "n. 恐慌，惊慌；大恐慌 adj. 恐慌的；没有理由的 vt. 使恐慌 vi. 十分惊慌" },
  { "en": "plea", "phonetic": "/pliː/", "zh": "n. 恳求，请求；辩解，辩护；借口，托辞" },
  { "en": "thirst", "phonetic": "/θɜːrst/", "zh": "n. 渴望；口渴；热望 vi. 渴望；口渴" },
  { "en": "likelihood", "phonetic": "/ˈlaɪklihʊd/", "zh": "n. 可能性，可能" },
  { "en": "reign", "phonetic": "/reɪn/", "zh": "n. 君主统治时期；任期；（运动员）持荣誉头衔时期；主宰期 v. 统治；成为最佳；盛行，支" },
  { "en": "sovereign", "phonetic": "/ˈsɑːvrɪn/", "zh": "n. 君主；独立国；金磅 adj. 至高无上的；有主权的；拥有最高统治权的；不折不" },
  { "en": "equilibrium", "phonetic": "/ˌiːkwɪˈlɪbriəm/", "zh": "n. 均衡；平静；保持平衡的能力" },
  { "en": "corps", "phonetic": "/kɔːr/", "zh": "n. 军团；兵种；兵队；（德国大学的）学生联合会" },
  { "en": "dismay", "phonetic": "/dɪsˈmeɪ/", "zh": "n. 沮丧，灰心；惊慌 vt. 使沮丧；使惊慌" },
  { "en": "spectacle", "phonetic": "/ˈspektəkl/", "zh": "n. 景象；场面；奇观；壮观；盛大的演出；（复）眼镜" },
  { "en": "elite", "phonetic": "/eɪˈliːt/", "zh": "n. 精英；精华；中坚分子" },
  { "en": "proficiency", "phonetic": "/prəˈfɪʃnsi/", "zh": "n. 精通，熟练" },
  { "en": "proceeding", "phonetic": "/prəˈsiːdɪŋ/", "zh": "n. 进行；程序；诉讼；事项 v. 开始；继续做；行进（proceed的ing形式）" },
  { "en": "pretext", "phonetic": "/ˈpriːtekst/", "zh": "n. 借口；托辞 vt. 以…为借口" },
  { "en": "verdict", "phonetic": "/ˈvɜːrdɪkt/", "zh": "n. 结论；裁定" },
  { "en": "masterpiece", "phonetic": "/ˈmæstərpiːs/", "zh": "n. 杰作；绝无仅有的人" },
  { "en": "relay", "phonetic": "/ˈriːleɪ,rɪˈleɪ/", "zh": "n. 接力赛；轮班，轮换；继电器；中继设备 v. 传达，转发；转播；重新铺设" },
  { "en": "proximity", "phonetic": "/prɑːkˈsɪməti/", "zh": "n. 接近，[数]邻近；接近；接近度，距离；亲近" },
  { "en": "script", "phonetic": "/skrɪpt/", "zh": "n. 脚本；手迹；书写用的字母 vt. 把…改编为剧本 vi. 写电影脚本" },
  { "en": "hinge", "phonetic": "/hɪndʒ/", "zh": "n. 铰链，折叶；关键，转折点；枢要，中枢 v. 用铰链连接；依…为转移；给…安装铰链；（门" },
  { "en": "tar", "phonetic": "/tɑːr/", "zh": "n. 焦油；柏油；水手 vt. 涂以焦油；玷污" },
  { "en": "capsule", "phonetic": "/ˈkæpsl,ˈkæpsuːl/", "zh": "n. 胶囊；蒴果；太空舱；小容器 adj. 压缩的；概要的 vt. 压缩；简述" },
  { "en": "transaction", "phonetic": "/trænˈzækʃn/", "zh": "n. 交易；事务；办理；会报，学报" },
  { "en": "symphony", "phonetic": "/ˈsɪmfəni/", "zh": "n. 交响乐；谐声，和声" },
  { "en": "intersection", "phonetic": "/ˌɪntərˈsekʃn/", "zh": "n. 交叉；十字路口；交集；交叉点" },
  { "en": "sauce", "phonetic": "/sɔːs/", "zh": "n. 酱油；沙司；调味汁 vt. 使增加趣味；给…调味" },
  { "en": "bonus", "phonetic": "/ˈboʊnəs/", "zh": "n. 奖金；红利；额外津贴" },
  { "en": "jail", "phonetic": "/dʒeɪl/", "zh": "n. 监狱；监牢；拘留所 vt. 监禁；下狱" },
  { "en": "spy", "phonetic": "/spaɪ/", "zh": "n. 间谍；密探 v. 从事间谍活动；突然看见；认出" },
  { "en": "hypothesis", "phonetic": "/haɪˈpɑːθəsɪs/", "zh": "n. 假设" },
  { "en": "successor", "phonetic": "/səkˈsesər/", "zh": "n. 继承者；后续的事物" },
  { "en": "jerk", "phonetic": "/dʒɜːrk/", "zh": "n. 急拉；猛的一动；肌肉抽搐；蠢人；没品的人 vi. 痉挛；急拉；颠簸地行进 vt. 猛拉 adj. 香" },
  { "en": "thrill", "phonetic": "/θrɪl/", "zh": "n. 激动；震颤；紧张 vt. 使…颤动；使…紧张；使…感到兴奋或激动 vi. 颤抖；感到兴奋；感到紧" },
  { "en": "agitation", "phonetic": "/ˌædʒɪˈteɪʃn/", "zh": "n. 激动；搅动；煽动；烦乱" },
  { "en": "mechanism", "phonetic": "/ˈmekənɪzəm/", "zh": "n. 机制；原理，途径；进程；机械装置；技巧" },
  { "en": "locomotive", "phonetic": "/ˌloʊkəˈmoʊtɪv/", "zh": "n. 机车；火车头；（学校啦啦队）节奏由慢到快的欢呼 adj. 产生动力的，与动" },
  { "en": "acquisition", "phonetic": "/ˌækwɪˈzɪʃn/", "zh": "n. 获得物，获得；收购" },
  { "en": "confusion", "phonetic": "/kənˈfjuːʒn/", "zh": "n. 混淆，混乱；困惑" },
  { "en": "mess", "phonetic": "/mes/", "zh": "n. 混乱；食堂，伙食团；困境；脏乱的东西 vt. 弄乱，弄脏；毁坏；使就餐 vi. 把事情弄糟；" },
  { "en": "retrospect", "phonetic": "/ˈretrəspekt/", "zh": "n. 回顾，追溯 vi. 回顾，追溯；回想 vt. 回顾；追忆" },
  { "en": "royalty", "phonetic": "/ˈrɔɪəlti/", "zh": "n. 皇室；版税；王权；专利税" },
  { "en": "illusion", "phonetic": "/ɪˈluːʒn/", "zh": "n. 幻觉，错觉；错误的观念或信仰" },
  { "en": "partition", "phonetic": "/pɑːrˈtɪʃn/", "zh": "n. 划分，分开；[数] 分割；隔墙；隔离物 vt. [数] 分割；分隔；区分" },
  { "en": "fossil", "phonetic": "/ˈfɑːsl/", "zh": "n. 化石；僵化的事物；顽固不化的人 adj. 化石的；陈腐的，守旧的" },
  { "en": "offspring", "phonetic": "/ˈɔːfsprɪŋ/", "zh": "n. 后代，子孙；产物" },
  { "en": "shuttle", "phonetic": "/ˈʃʌtl/", "zh": "n. 航天飞机；穿梭；梭子；穿梭班机、公共汽车等 vt. 使穿梭般来回移动；短程穿梭般运送" },
  { "en": "vi.", "phonetic": "", "zh": "穿梭往返" },
  { "en": "pest", "phonetic": "/pest/", "zh": "n. 害虫；有害之物；讨厌的人" },
  { "en": "poster", "phonetic": "/ˈpoʊstər/", "zh": "n. 海报，广告；招贴" },
  { "en": "transition", "phonetic": "/trænˈsɪʃn/", "zh": "n. 过渡；转变；[分子生物] 转换；变调" },
  { "en": "specification", "phonetic": "/ˌspesɪfɪˈkeɪʃn/", "zh": "n. 规格；说明书；详述" },
  { "en": "spectrum", "phonetic": "/ˈspektrəm/", "zh": "n. 光谱；频谱；范围；余象" },
  { "en": "irrigation", "phonetic": "/ˌɪrɪˈɡeɪʃn/", "zh": "n. 灌溉；[临床] 冲洗；冲洗法" },
  { "en": "spectator", "phonetic": "/ˈspekteɪtər/", "zh": "n. 观众；旁观者" },
  { "en": "tariff", "phonetic": "/ˈtærɪf/", "zh": "n. 关税表；收费表 vt. 定税率；征收关税" },
  { "en": "monster", "phonetic": "/ˈmɑːnstər/", "zh": "n. 怪物；巨人，巨兽；残忍的人 adj. 巨大的，庞大的" },
  { "en": "consultant", "phonetic": "/kənˈsʌltənt/", "zh": "n. 顾问；咨询者；会诊医生" },
  { "en": "skeleton", "phonetic": "/ˈskelɪtn/", "zh": "n. 骨架，骨骼；纲要；骨瘦如柴的人 adj. 骨骼的；骨瘦如柴的；概略的" },
  { "en": "cereal", "phonetic": "/ˈsɪriəl/", "zh": "n. 谷类，谷物；谷类食品；谷类植物 adj. 谷类的；谷类制成的" },
  { "en": "trench", "phonetic": "/trentʃ/", "zh": "n. 沟，沟渠；战壕；堑壕 vt. 掘沟 vi. 挖战壕；侵害" },
  { "en": "assault", "phonetic": "/əˈsɔːlt/", "zh": "n. 攻击；袭击 vt. 攻击；袭击 vi. 袭击；动武" },
  { "en": "studio", "phonetic": "/ˈstuːdioʊ/", "zh": "n. 工作室；[广播][电视] 演播室；画室；电影制片厂" },
  { "en": "kit", "phonetic": "/kɪt/", "zh": "n. 工具箱；成套工具 vt. 装备 vi. 装备" },
  { "en": "replacement", "phonetic": "/rɪˈpleɪsmənt/", "zh": "n. 更换；复位；代替者；补充兵员" },
  { "en": "warrant", "phonetic": "/ˈwɔːrənt/", "zh": "n. 根据；证明；正当理由；委任状 vt. 保证；担保；批准；辩解" },
  { "en": "lamb", "phonetic": "/læm/", "zh": "n. 羔羊，小羊；羔羊肉 vt. 生小羊，产羔羊 vi. 生小羊，产羔羊" },
  { "en": "plateau", "phonetic": "/plæˈtoʊ/", "zh": "n. 高原；稳定水平；托盘；平顶女帽 vi. 达到平衡；达到稳定时期" },
  { "en": "disturbance", "phonetic": "/dɪˈstɜːrbəns/", "zh": "n. 干扰；骚乱；忧虑" },
  { "en": "sentiment", "phonetic": "/ˈsentɪmənt/", "zh": "n. 感情，情绪；情操；观点；多愁善感" },
  { "en": "sensation", "phonetic": "/senˈseɪʃn/", "zh": "n. 感觉；轰动；感动" },
  { "en": "Thanksgiving", "phonetic": "/ˌθæŋksˈɡɪvɪŋ/", "zh": "n. 感恩" },
  { "en": "notion", "phonetic": "/ˈnoʊʃn/", "zh": "n. 概念；见解；打算" },
  { "en": "costume", "phonetic": "/ˈkɑːstuːm/", "zh": "n. 服装，装束；戏装，剧装 vt. 给…穿上服装" },
  { "en": "hatch", "phonetic": "/hætʃ/", "zh": "n. 孵化；舱口 vt. 孵；策划 vi. 孵化" },
  { "en": "veto", "phonetic": "/ˈviːtoʊ/", "zh": "n. 否决权 vt. 否决；禁止 vi. 否决；禁止" },
  { "en": "seam", "phonetic": "/siːm/", "zh": "n. 缝；接缝 vt. 缝合；接合；使留下伤痕 vi. 裂开；产生裂缝" },
  { "en": "irony", "phonetic": "/ˈaɪrəni/", "zh": "n. 讽刺；反语；具有讽刺意味的事 adj. 铁的；似铁的" },
  { "en": "rage", "phonetic": "/reɪdʒ/", "zh": "n. 愤怒；狂暴，肆虐；情绪激动 vi. 大怒，发怒；流行，风行" },
  { "en": "indignation", "phonetic": "/ˌɪndɪɡˈneɪʃn/", "zh": "n. 愤慨；愤怒；义愤" },
  { "en": "orientation", "phonetic": "/ˌɔːriənˈteɪʃn/", "zh": "n. 方向；定向；适应；情况介绍" },
  { "en": "offence", "phonetic": "/əˈfens/", "zh": "n. 犯罪；违反；过错；攻击" },
  { "en": "turnover", "phonetic": "/ˈtɜːrnoʊvər/", "zh": "n. 翻覆；[贸易] 营业额；流通量；半圆卷饼；失误 adj. 翻过来的；可翻转的" },
  { "en": "valve", "phonetic": "/vælv/", "zh": "n. 阀；[解剖] 瓣膜；真空管；活门 vt. 装阀于；以活门调节" },
  { "en": "penalty", "phonetic": "/ˈpenəlti/", "zh": "n. 罚款，罚金；处罚" },
  { "en": "spokesman", "phonetic": "/ˈspoʊksmən/", "zh": "n. 发言人；代言人" },
  { "en": "nightmare", "phonetic": "/ˈnaɪtmer/", "zh": "n. 恶梦，噩梦；梦魇般的经历 adj. 可怕的；噩梦似的" },
  { "en": "yoke", "phonetic": "/joʊk/", "zh": "n. 轭；束缚；牛轭 vt. 结合；给…上轭 vi. 结合；匹配" },
  { "en": "premium", "phonetic": "/ˈpriːmiəm/", "zh": "n. 额外费用；奖金；保险费；溢价 adj. 高价的；优质的" },
  { "en": "symmetry", "phonetic": "/ˈsɪmətri/", "zh": "n. 对称（性）；整齐，匀称" },
  { "en": "segment", "phonetic": "/ˈseɡmənt/", "zh": "n. 段，部分；（水果或花的）瓣，（动物的）节；弓形；音段；（广播或节目的）时间段" },
  { "en": "literacy", "phonetic": "/ˈlɪtərəsi/", "zh": "n. 读写能力；精通文学" },
  { "en": "solo", "phonetic": "/ˈsoʊloʊ/", "zh": "n. 独奏；独唱；独奏曲 adj. 独奏的；独唱的；单独的 vt. 单人攀登；单独驾 vi. 单独表演；" },
  { "en": "impetus", "phonetic": "/ˈɪmpɪtəs/", "zh": "n. 动力；促进；冲力；动量" },
  { "en": "incentive", "phonetic": "/ɪnˈsentɪv/", "zh": "n. 动机；刺激" },
  { "en": "summit", "phonetic": "/ˈsʌmɪt/", "zh": "n. 顶点；最高级会议；最高阶层 adj. 最高级的；政府首脑的" },
  { "en": "sculpture", "phonetic": "/ˈskʌlptʃər/", "zh": "n. 雕塑；雕刻；刻蚀 vt. 雕塑；雕刻；刻蚀 vi. 从事雕刻" },
  { "en": "refreshment", "phonetic": "/rɪˈfreʃmənt/", "zh": "n. 点心；起提神作用的东西；精力恢复" },
  { "en": "mortgage", "phonetic": "/ˈmɔːrɡɪdʒ/", "zh": "n. 抵押；抵押贷款额 v. 抵押；以某人的前途作代价" },
  { "en": "murmur", "phonetic": "/ˈmɜːrmər/", "zh": "n. 低语；低语声；低声抱怨；潺潺声 vi. 低声说；私下抱怨；发出轻柔持续的声音 vt." },
  { "en": "rating", "phonetic": "/ˈreɪtɪŋ/", "zh": "n. 等级；等级评定；额定功率 v. 对…评价（rate的ing形式）" },
  { "en": "Mediterranean", "phonetic": "/ˌmedɪtəˈreɪniən/", "zh": "n. 地中海 adj. 地中海的" },
  { "en": "morality", "phonetic": "/məˈræləti/", "zh": "n. 道德；品行，美德" },
  { "en": "theft", "phonetic": "/θeft/", "zh": "n. 盗窃；偷；赃物" },
  { "en": "tutor", "phonetic": "/ˈtuːtər/", "zh": "n. 导师；家庭教师；助教；（尤指音乐）课本 v. 辅导；约束；当家庭教师，当大学导师" },
  { "en": "midst", "phonetic": "/mɪdst/", "zh": "n. 当中，中间 prep. 在…中间（等于amidst）" },
  { "en": "representation", "phonetic": "/ˌreprɪzenˈteɪʃn/", "zh": "n. 代表；表现；表示法；陈述" },
  { "en": "magnitude", "phonetic": "/ˈmæɡnɪtuːd/", "zh": "n. 大小；量级；[地震] 震级；重要；光度" },
  { "en": "lobby", "phonetic": "/ˈlɑːbi/", "zh": "n. 大厅；休息室；会客室；游说议员的团体 vt. 对……进行游说 vi. 游说议员" },
  { "en": "multitude", "phonetic": "/ˈmʌltɪtuːd/", "zh": "n. 大量，多数；群众，人群" },
  { "en": "marble", "phonetic": "/ˈmɑːrbl/", "zh": "n. 大理石；大理石制品；弹珠 adj. 大理石的；冷酷无情的" },
  { "en": "stride", "phonetic": "/straɪd/", "zh": "n. 大步；步幅；进展 vt. 跨过；大踏步走过；跨坐在… vi. 跨；跨过；大步行走" },
  { "en": "inventory", "phonetic": "/ˈɪnvəntɔːri/", "zh": "n. 存货，存货清单；详细目录；财产清册 vt. 给……开列清单" },
  { "en": "stimulus", "phonetic": "/ˈstɪmjələs/", "zh": "n. 刺激；激励；刺激物" },
  { "en": "thorn", "phonetic": "/θɔːrn/", "zh": "n. 刺；荆棘" },
  { "en": "tile", "phonetic": "/taɪl/", "zh": "n. 瓷砖，瓦片 vt. 铺以瓦；铺以瓷砖" },
  { "en": "innovation", "phonetic": "/ˌɪnəˈveɪʃn/", "zh": "n. 创新，革新；新方法" },
  { "en": "legend", "phonetic": "/ˈledʒənd/", "zh": "n. 传奇；说明；图例；刻印文字" },
  { "en": "romance", "phonetic": "/ˈroʊmæns/", "zh": "n. 传奇；浪漫史；风流韵事；冒险故事 vi. 虚构；渲染；写传奇" },
  { "en": "missionary", "phonetic": "/ˈmɪʃəneri/", "zh": "n. 传教士 adj. 传教的；传教士的；传教士般的" },
  { "en": "disposition", "phonetic": "/ˌdɪspəˈzɪʃn/", "zh": "n. 处置；[心理] 性情；[军] 部署；倾向" },
  { "en": "scandal", "phonetic": "/ˈskændl/", "zh": "n. 丑闻；流言蜚语；诽谤；公愤" },
  { "en": "deficit", "phonetic": "/ˈdefɪsɪt/", "zh": "n. 赤字；不足额" },
  { "en": "tenant", "phonetic": "/ˈtenənt/", "zh": "n. 承租人；房客；佃户；居住者 vt. 租借（常用于被动语态）" },
  { "en": "commitment", "phonetic": "/kəˈmɪtmənt/", "zh": "n. 承诺，保证；委托；承担义务；献身；花费金钱、时间、人力等" },
  { "en": "constituent", "phonetic": "/kənˈstɪtʃuənt/", "zh": "n. 成分；选民；委托人 adj. 构成的；选举的；有任命（或选举）权的；立宪" },
  { "en": "stereotype", "phonetic": "/ˈsteriətaɪp/", "zh": "n. 陈腔滥调，老套；成见；模式化形象；铅版，铅版（浇铸或印刷） v. 对……形成" },
  { "en": "quiver", "phonetic": "/ˈkwɪvər/", "zh": "n. 颤抖；箭袋；震动 vi. 颤抖；振动 vt. 使…颤动；抖动" },
  { "en": "hierarchy", "phonetic": "/ˈhaɪərɑːrki/", "zh": "n. 层级；等级制度" },
  { "en": "tactics", "phonetic": "/ˈtæktɪks/", "zh": "n. 策略；战术；用兵学" },
  { "en": "profile", "phonetic": "/ˈproʊfaɪl/", "zh": "n. 侧面；轮廓；外形；剖面；简况 vt. 描…的轮廓；扼要描述 vi. 给出轮廓" },
  { "en": "flank", "phonetic": "/flæŋk/", "zh": "n. 侧面；侧翼；侧腹 vt. 守侧面；位于…的侧面；攻击侧面 vi. 侧面与…相接 adv. 在左右两" },
  { "en": "meadow", "phonetic": "/ˈmedoʊ/", "zh": "n. 草地；牧场" },
  { "en": "pasture", "phonetic": "/ˈpæstʃər/", "zh": "n. 草地；牧场；牧草 vt. 放牧；吃草" },
  { "en": "warehouse", "phonetic": "/ˈwerhaʊs/", "zh": "n. 仓库；货栈；大商店 vt. 储入仓库；以他人名义购进（股票）" },
  { "en": "participant", "phonetic": "/pɑːrˈtɪsɪpənt/", "zh": "n. 参与者，参加者 adj. 参与的" },
  { "en": "senator", "phonetic": "/ˈsenətər/", "zh": "n. 参议员；（古罗马的）元老院议员；评议员，理事" },
  { "en": "parameter", "phonetic": "/pəˈræmɪtər/", "zh": "n. 参数；系数；参量" },
  { "en": "subordinate", "phonetic": "/səˈbɔːrdɪnət/", "zh": "n. 部属，下属，下级；从属，次要 vt. 使……居下位；使……服从 adj. 从属的，" },
  { "en": "sector", "phonetic": "/ˈsektər/", "zh": "n. 部门；扇形，扇区；象限仪；函数尺 vt. 把…分成扇形" },
  { "en": "tribe", "phonetic": "/traɪb/", "zh": "n. 部落；族；宗族；一伙" },
  { "en": "misfortune", "phonetic": "/ˌmɪsˈfɔːrtʃən/", "zh": "n. 不幸；灾祸，灾难" },
  { "en": "discrepancy", "phonetic": "/dɪˈskrepənsi/", "zh": "n. 不符；矛盾；相差" },
  { "en": "subsidy", "phonetic": "/ˈsʌbsədi/", "zh": "n. 补贴；津贴；补助金" },
  { "en": "exposition", "phonetic": "/ˌekspəˈzɪʃn/", "zh": "n. 博览会；阐述；展览会" },
  { "en": "ripple", "phonetic": "/ˈrɪpl/", "zh": "n. 波纹；涟漪；[物] 涟波 vi. 起潺潺声 vt. 在…上形成波痕" },
  { "en": "ward", "phonetic": "/wɔːrd/", "zh": "n. 病房；保卫；监视；区，选区 vt. 避开；保卫；守护" },
  { "en": "norm", "phonetic": "/nɔːrm/", "zh": "n. 标准，规范" },
  { "en": "slogan", "phonetic": "/ˈsloʊɡən/", "zh": "n. 标语；呐喊声" },
  { "en": "fringe", "phonetic": "/frɪndʒ/", "zh": "n. 边缘；穗；刘海 adj. 边缘的；附加的 vt. 加穗于" },
  { "en": "verge", "phonetic": "/vɜːrdʒ/", "zh": "n. 边缘；绿地；极限；山墙突瓦；权杖（作为职位标志） v. 濒临，接近；趋向；处在边缘" },
  { "en": "rim", "phonetic": "/rɪm/", "zh": "n. 边，边缘；轮辋；圆圈 vi. 作…的边，装边于 vt. 作…的边，装边于" },
  { "en": "essence", "phonetic": "/ˈesns/", "zh": "n. 本质，实质；精华；香精" },
  { "en": "paradox", "phonetic": "/ˈpærədɑːks/", "zh": "n. 悖论，反论；似是而非的论点；自相矛盾的人或事 n. （Paradox）《杀破狼：贪狼》" },
  { "en": "tablet", "phonetic": "/ˈtæblət/", "zh": "n. 碑；药片；写字板；小块；平板电脑 vt. 用碑牌纪念；将(备忘录等)写在板上；将…制" },
  { "en": "grief", "phonetic": "/ɡriːf/", "zh": "n. 悲痛；忧伤；不幸" },
  { "en": "riot", "phonetic": "/ˈraɪət/", "zh": "n. 暴乱；放纵；蔓延 vi. 骚乱；放荡 vt. 浪费，挥霍" },
  { "en": "messenger", "phonetic": "/ˈmesɪndʒər/", "zh": "n. 报信者，送信者；先驱" },
  { "en": "revenge", "phonetic": "/rɪˈvendʒ/", "zh": "n. 报复；复仇 vt. 报复；替…报仇；洗雪 vi. 报仇；雪耻" },
  { "en": "fort", "phonetic": "/fɔːrt/", "zh": "n. 堡垒；要塞；（美）边界贸易站 vt. 设要塞保卫 vi. 构筑要塞" },
  { "en": "pledge", "phonetic": "/pledʒ/", "zh": "n. 保证，誓言；抵押；抵押品，典当物 vt. 保证，许诺；用……抵押；举杯祝……健康" },
  { "en": "retention", "phonetic": "/rɪˈtenʃn/", "zh": "n. 保留；扣留，滞留；记忆力；闭尿" },
  { "en": "safeguard", "phonetic": "/ˈseɪfɡɑːrd/", "zh": "n. 保护；保卫；保护措施；预防措施 v. 保护；护卫" },
  { "en": "liner", "phonetic": "/ˈlaɪnər/", "zh": "n. 班轮，班机；衬垫；画线者" },
  { "en": "wrench", "phonetic": "/rentʃ/", "zh": "n. 扳手，扳钳；扭伤；痛苦；歪曲；猛扭 vt. 扭伤；猛扭；曲解；折磨 vi. 扭伤；猛扭；猛" },
  { "en": "trigger", "phonetic": "/ˈtrɪɡər/", "zh": "n. 扳机；起因，引起反应的事；触发器，引爆装置 v. 触发，引起；开动（装置）" },
  { "en": "knob", "phonetic": "/nɑːb/", "zh": "n. 把手；瘤；球形突出物 vi. 鼓起 vt. 使有球形突出物" },
  { "en": "installment", "phonetic": "/ɪnˈstɔːlmənt/", "zh": "n. 安装；分期付款；部分；就职" },
  { "en": "manuscript", "phonetic": "/ˈmænjuskrɪpt/", "zh": "n. [图情] 手稿；原稿 adj. 手写的" },
  { "en": "galaxy", "phonetic": "/ˈɡæləksi/", "zh": "n. [天] 星系；银河系（the Galaxy）；一群显赫的人 n. 三星智能手机品牌 2015年三星" },
  { "en": "remainder", "phonetic": "/rɪˈmeɪndər/", "zh": "n. [数] 余数，残余；剩余物；其余的人 adj. 剩余的；吃剩的 vt. 廉价出售；削价出" },
  { "en": "species", "phonetic": "/ˈspiːʃiːz/", "zh": "n. [生物] 物种；种类 adj. 物种上的" },
  { "en": "suitcase", "phonetic": "/ˈsuːtkeɪs/", "zh": "n. [轻] 手提箱；衣箱" },
  { "en": "humidity", "phonetic": "/hjuːˈmɪdəti/", "zh": "n. [气象] 湿度；湿气" },
  { "en": "symptom", "phonetic": "/ˈsɪmptəm/", "zh": "n. [临床] 症状；征兆" },
  { "en": "inertia", "phonetic": "/ɪˈnɜːrʃə/", "zh": "n. [力] 惯性；惰性，迟钝；不活动" },
  { "en": "resonance", "phonetic": "/ˈrezənəns/", "zh": "n. [力] 共振；共鸣；反响" },
  { "en": "kidney", "phonetic": "/ˈkɪdni/", "zh": "n. [解剖] 肾脏；腰子；个性" },
  { "en": "validity", "phonetic": "/vəˈlɪdəti/", "zh": "n. [计] 有效性；正确；正确性" },
  { "en": "option", "phonetic": "/ˈɑːpʃn/", "zh": "n. [计] 选项；选择权；买卖的特权" },
  { "en": "oxide", "phonetic": "/ˈɑːksaɪd/", "zh": "n. [化学] 氧化物" },
  { "en": "silicon", "phonetic": "/ˈsɪlɪkən/", "zh": "n. [化学] 硅；硅元素" },
  { "en": "purity", "phonetic": "/ˈpjʊrəti/", "zh": "n. [化学] 纯度；纯洁；纯净；纯粹" },
  { "en": "testimony", "phonetic": "/ˈtestɪmoʊni/", "zh": "n. [法] 证词，证言；证据" },
  { "en": "jury", "phonetic": "/ˈdʒʊri/", "zh": "n. [法] 陪审团；评判委员会 adj. 应急的" },
  { "en": "heir", "phonetic": "/er/", "zh": "n. [法] 继承人；后嗣；嗣子" },
  { "en": "epoch", "phonetic": "/ˈepək/", "zh": "n. [地质] 世；新纪元；新时代；时间上的一点" },
  { "en": "longitude", "phonetic": "/ˈlɑːndʒɪtuːd/", "zh": "n. [地理] 经度；经线" },
  { "en": "terrain", "phonetic": "/təˈreɪn/", "zh": "n. [地理] 地形，地势；领域；地带" },
  { "en": "virus", "phonetic": "/ˈvaɪrəs/", "zh": "n. [病毒] 病毒；恶毒；毒害" },
  { "en": "renaissance", "phonetic": "/ˈrenəsɑːns/", "zh": "n. （艺术等的）新生，复活 n. (Renaissance) 文艺复兴，文艺复兴风格" },
  { "en": "pore", "phonetic": "/pɔːr/", "zh": "n. （皮肤上的）毛孔；（植物的）气孔，孔隙 v. 仔细打量，审视；凝视；认真研读，审阅；深" },
  { "en": "criterion", "phonetic": "/kraɪˈtɪriən/", "zh": "n. （批评判断的）标准；准则；规范；准据" },
  { "en": "pedal", "phonetic": "/ˈpedl/", "zh": "n. （车辆，乐器的）踏板 v. 骑（自行车）；踩踏板 adj. 脚的；脚踏的" },
  { "en": "whereas", "phonetic": "/ˌwerˈæz/", "zh": "conj. 然而；鉴于 n. 序言，开场白；条件语句" },
  { "en": "whereby", "phonetic": "/werˈbaɪ/", "zh": "conj. 凭借；通过…；借以；与…一致 adv. 凭此；借以" },
  { "en": "invariably", "phonetic": "/ɪnˈveriəbli/", "zh": "adv. 总是；不变地；一定地" },
  { "en": "specifically", "phonetic": "/spəˈsɪfɪkli/", "zh": "adv. 特别地；明确地" },
  { "en": "incidentally", "phonetic": "/ˌɪnsɪˈdentli/", "zh": "adv. 顺便；偶然地；附带地" },
  { "en": "readily", "phonetic": "/ˈredɪli/", "zh": "adv. 容易地；乐意地；无困难地" },
  { "en": "hitherto", "phonetic": "/ˌhɪðərˈtuː/", "zh": "adv. 迄今；至今" },
  { "en": "thereafter", "phonetic": "/ˌðerˈæftər/", "zh": "adv. 其后；从那时以后" },
  { "en": "seemingly", "phonetic": "/ˈsiːmɪŋli/", "zh": "adv. 看来似乎；表面上看来" },
  { "en": "presumably", "phonetic": "/prɪˈzuːməbli/", "zh": "adv. 大概；推测起来；可假定" },
  { "en": "articulate", "phonetic": "/ɑːrˈtɪkjuleɪt/", "zh": "adj.有关节的,发音清晰的 vt.用关节连接,接合,清晰明白地说" },
  { "en": "nasty", "phonetic": "/ˈnæsti/", "zh": "adj.污秽的,肮脏的,令人厌恶的,淫秽的,下流的,凶相的,威胁的" },
  { "en": "spiral", "phonetic": "/ˈspaɪrəl/", "zh": "adj.螺旋形的 n.螺旋 v.盘旋" },
  { "en": "optimum", "phonetic": "/ˈɑːptɪməm/", "zh": "adj. 最适宜的 n. 最佳效果；最适宜条件" },
  { "en": "minimal", "phonetic": "/ˈmɪnɪml/", "zh": "adj. 最低的；最小限度的" },
  { "en": "spontaneous", "phonetic": "/spɑːnˈteɪniəs/", "zh": "adj. 自发的；自然的；无意识的" },
  { "en": "ultraviolet", "phonetic": "/ˌʌltrəˈvaɪələt/", "zh": "adj. 紫外的；紫外线的 n. 紫外线辐射，紫外光" },
  { "en": "spectacular", "phonetic": "/spekˈtækjələr/", "zh": "adj. 壮观的，惊人的；公开展示的" },
  { "en": "residential", "phonetic": "/ˌrezɪˈdenʃl/", "zh": "adj. 住宅的；与居住有关的" },
  { "en": "predominant", "phonetic": "/prɪˈdɑːmɪnənt/", "zh": "adj. 主要的；卓越的；支配的；有力的；有影响的" },
  { "en": "subjective", "phonetic": "/səbˈdʒektɪv/", "zh": "adj. 主观的；个人的；自觉的" },
  { "en": "periodic", "phonetic": "/ˌpɪriˈɑːdɪk/", "zh": "adj. 周期的；定期的" },
  { "en": "crucial", "phonetic": "/ˈkruːʃl/", "zh": "adj. 重要的；决定性的；定局的；决断的" },
  { "en": "ethnic", "phonetic": "/ˈeθnɪk/", "zh": "adj. 种族的；人种的" },
  { "en": "medieval", "phonetic": "/ˌmediˈiːvl,ˌmiːdˈiːvl/", "zh": "adj. 中世纪的；原始的；仿中世纪的；老式的" },
  { "en": "vocational", "phonetic": "/voʊˈkeɪʃənl/", "zh": "adj. 职业的，行业的" },
  { "en": "notable", "phonetic": "/ˈnoʊtəbl/", "zh": "adj. 值得注意的，显著的；著名的 n. 名人，显要人物" },
  { "en": "authentic", "phonetic": "/ɔːˈθentɪk/", "zh": "adj. 真正的，真实的；可信的" },
  { "en": "strategic", "phonetic": "/strəˈtiːdʒɪk/", "zh": "adj. 战略上的，战略的" },
  { "en": "premature", "phonetic": "/ˌpriːməˈtʃʊr,ˌpriːməˈtʊr/", "zh": "adj. 早产的；不成熟的；比预期早的 n. 早产儿；过早发生的事物" },
  { "en": "lunar", "phonetic": "/ˈluːnər/", "zh": "adj. 月亮的，月球的；阴历的；银的；微亮的" },
  { "en": "controversial", "phonetic": "/ˌkɑːntrəˈvɜːrʃl/", "zh": "adj. 有争议的；有争论的" },
  { "en": "promising", "phonetic": "/ˈprɑːmɪsɪŋ/", "zh": "adj. 有希望的，有前途的 v. 许诺，答应（promise的现在分词形式）" },
  { "en": "profitable", "phonetic": "/ˈprɑːfɪtəbl/", "zh": "adj. 有利可图的；赚钱的；有益的" },
  { "en": "ingenious", "phonetic": "/ɪnˈdʒiːniəs/", "zh": "adj. 有独创性的；机灵的，精制的；心灵手巧的" },
  { "en": "resultant", "phonetic": "/rɪˈzʌltənt/", "zh": "adj. 由此导致的，因而发生的 n. 合力，合成速率；结果" },
  { "en": "perpetual", "phonetic": "/pərˈpetʃuəl/", "zh": "adj. 永久的；不断的；四季开花的；无期限的" },
  { "en": "obscene", "phonetic": "/əbˈsiːn/", "zh": "adj. 淫秽的；猥亵的；可憎的" },
  { "en": "bleak", "phonetic": "/bliːk/", "zh": "adj. 阴冷的；荒凉的，无遮蔽的；黯淡的，无希望的；冷酷的；单调的" },
  { "en": "eloquent", "phonetic": "/ˈeləkwənt/", "zh": "adj. 意味深长的；雄辩的，有口才的；有说服力的；动人的" },
  { "en": "brittle", "phonetic": "/ˈbrɪtl/", "zh": "adj. 易碎的，脆弱的；易生气的" },
  { "en": "susceptible", "phonetic": "/səˈseptəbl/", "zh": "adj. 易受影响的；易感动的；容许……的 n. 易得病的人" },
  { "en": "vulnerable", "phonetic": "/ˈvʌlnərəbl/", "zh": "adj. 易受攻击的，易受……的攻击；易受伤害的；有弱点的" },
  { "en": "exotic", "phonetic": "/ɪɡˈzɑːtɪk/", "zh": "adj. 异国的；外来的；异国情调的" },
  { "en": "compulsory", "phonetic": "/kəmˈpʌlsəri/", "zh": "adj. 义务的；必修的；被强制的 n. （花样滑冰、竞技体操等的）规定动作" },
  { "en": "savage", "phonetic": "/ˈsævɪdʒ/", "zh": "adj. 野蛮的；残酷的；狂怒的；荒凉的 n. 未开化的人；粗鲁的人；残暴成性的人 vt. 乱" },
  { "en": "grim", "phonetic": "/ɡrɪm/", "zh": "adj. 严肃的；令人沮丧的；阴沉的；糟糕的" },
  { "en": "stern", "phonetic": "/stɜːrn/", "zh": "adj. 严厉的；坚定的；严峻的；认真的 n. 船尾；末端；（幽默）（人的）臀部" },
  { "en": "rigorous", "phonetic": "/ˈrɪɡərəs/", "zh": "adj. 严格的，严厉的；严密的；严酷的" },
  { "en": "sexual", "phonetic": "/ˈsekʃuəl/", "zh": "adj. 性的；性别的；有性的" },
  { "en": "hysterical", "phonetic": "/hɪˈsterɪkl/", "zh": "adj. 歇斯底里的；异常兴奋的" },
  { "en": "indicative", "phonetic": "/ɪnˈdɪkətɪv/", "zh": "adj. 象征的；指示的；表示…的 n. 陈述语气；陈述语气的动词形式" },
  { "en": "linear", "phonetic": "/ˈlɪniər/", "zh": "adj. 线的，线型的；直线的，线状的；长度的" },
  { "en": "realistic", "phonetic": "/ˌriːəˈlɪstɪk/", "zh": "adj. 现实的；现实主义的；逼真的；实在论的" },
  { "en": "conspicuous", "phonetic": "/kənˈspɪkjuəs/", "zh": "adj. 显著的；显而易见的" },
  { "en": "striking", "phonetic": "/ˈstraɪkɪŋ/", "zh": "adj. 显著的，突出的，惊人的；打击的；罢工的 v. 打（strike的ing形式）" },
  { "en": "invalid", "phonetic": "/ɪnˈvælɪd/", "zh": "adj. 无效的；有病的；残疾的 n. 病人；残疾者 vt. 使伤残；使退役 vi. 变得病弱；因" },
  { "en": "void", "phonetic": "/vɔɪd/", "zh": "adj. 无效的；空的；无人（居住）的；缺乏的 n. 空间；空白；空虚感 v. 使无效；排放（大小便）" },
  { "en": "invaluable", "phonetic": "/ɪnˈvæljuəbl/", "zh": "adj. 无价的；非常贵重的" },
  { "en": "literal", "phonetic": "/ˈlɪtərəl/", "zh": "adj. 文字的；逐字的；无夸张的" },
  { "en": "situated", "phonetic": "/ˈsɪtʃueɪtɪd/", "zh": "adj. 位于…的；处于…境遇的 v. 使位于；使处于（situate的过去分词）" },
  { "en": "prospective", "phonetic": "/prəˈspektɪv/", "zh": "adj. 未来的；预期的" },
  { "en": "miniature", "phonetic": "/ˈmɪnətʃər,ˈmɪnətʃʊr/", "zh": "adj. 微型的，小规模的 n. 缩图；微型画；微型图画绘画术 vt. 是…的" },
  { "en": "feeble", "phonetic": "/ˈfiːbl/", "zh": "adj. 微弱的，无力的；虚弱的；薄弱的" },
  { "en": "subtle", "phonetic": "/ˈsʌtl/", "zh": "adj. 微妙的；精细的；敏感的；狡猾的；稀薄的" },
  { "en": "negligible", "phonetic": "/ˈneɡlɪdʒəbl/", "zh": "adj. 微不足道的，可以忽略的" },
  { "en": "marginal", "phonetic": "/ˈmɑːrdʒɪnl/", "zh": "adj. 微不足道的，不重要的；边缘的；临界的；末端的 n. 边缘席位" },
  { "en": "stubborn", "phonetic": "/ˈstʌbərn/", "zh": "adj. 顽固的；顽强的；难处理的" },
  { "en": "intact", "phonetic": "/ɪnˈtækt/", "zh": "adj. 完整的；原封不动的；未受损伤的" },
  { "en": "oval", "phonetic": "/ˈoʊvl/", "zh": "adj. 椭圆的；卵形的 n. 椭圆形；卵形" },
  { "en": "pedestrian", "phonetic": "/pəˈdestriən/", "zh": "adj. 徒步的；缺乏想像力的 n. 行人；步行者" },
  { "en": "simultaneous", "phonetic": "/ˌsaɪmlˈteɪniəs/", "zh": "adj. 同时的；联立的；同时发生的 n. 同时译员" },
  { "en": "naive", "phonetic": "/naɪˈiːv/", "zh": "adj. 天真的,幼稚的" },
  { "en": "ceramic", "phonetic": "/səˈræmɪk/", "zh": "adj. 陶瓷的；陶器的；制陶艺术的 n. 陶瓷；陶瓷制品" },
  { "en": "petty", "phonetic": "/ˈpeti/", "zh": "adj. 琐碎的；小气的；小规模的" },
  { "en": "instantaneous", "phonetic": "/ˌɪnstənˈteɪniəs/", "zh": "adj. 瞬间的；即时的；猝发的" },
  { "en": "obedient", "phonetic": "/əˈbiːdiənt/", "zh": "adj. 顺从的，服从的；孝顺的" },
  { "en": "watertight", "phonetic": "/ˈwɔːtərtaɪt/", "zh": "adj. 水密的；不漏水的；无懈可击的" },
  { "en": "numerical", "phonetic": "/nuːˈmerɪkl/", "zh": "adj. 数值的；数字的；用数字表示的（等于numeric）" },
  { "en": "tentative", "phonetic": "/ˈtentətɪv/", "zh": "adj. 试验性的，暂定的；踌躇的 n. 假设，试验" },
  { "en": "municipal", "phonetic": "/mjuːˈnɪsɪpl/", "zh": "adj. 市政的，市的；地方自治的" },
  { "en": "notorious", "phonetic": "/noʊˈtɔːriəs/", "zh": "adj. 声名狼藉的，臭名昭著的" },
  { "en": "esthetic", "phonetic": "/esˈθetɪk/", "zh": "adj. 审美的（等于aesthetic）；感觉的 n. 美学；审美家；唯美主义者" },
  { "en": "divine", "phonetic": "/dɪˈvaɪn/", "zh": "adj. 神圣的；非凡的；天赐的；极好的 vt. 占卜；预言；用占卜勘探 vi. 占卜；预言；" },
  { "en": "profound", "phonetic": "/prəˈfaʊnd/", "zh": "adj. 深厚的；意义深远的；渊博的" },
  { "en": "extravagant", "phonetic": "/ɪkˈstrævəɡənt/", "zh": "adj. 奢侈的；浪费的；过度的；放纵的" },
  { "en": "triple", "phonetic": "/ˈtrɪpl/", "zh": "adj. 三倍的；三方的 n. 三倍数；三个一组 vi. 增至三倍 vt. 使成三倍" },
  { "en": "limp", "phonetic": "/lɪmp/", "zh": "adj. 柔软的，无力的；软弱的 vi. 跛行，一拐一拐地走；缓慢费力地前进 n. 跛行" },
  { "en": "cordial", "phonetic": "/ˈkɔːrdʒəl/", "zh": "adj. 热情友好的；由衷的；兴奋的 n. 甜果汁饮料；镇定药；兴奋剂；甜香酒" },
  { "en": "thermal", "phonetic": "/ˈθɜːrml/", "zh": "adj. 热的；热量的；保热的 n. 上升的热气流" },
  { "en": "unanimous", "phonetic": "/juˈnænɪməs/", "zh": "adj. 全体一致的；意见一致的；无异议的" },
  { "en": "adolescent", "phonetic": "/ˌædəˈlesnt/", "zh": "adj. 青春期的；未成熟的 n. 青少年" },
  { "en": "robust", "phonetic": "/roʊˈbʌst/", "zh": "adj. 强健的；健康的；粗野的；粗鲁的" },
  { "en": "formidable", "phonetic": "/fəˈmɪdəbl/", "zh": "adj. 强大的；可怕的；令人敬畏的；艰难的" },
  { "en": "latent", "phonetic": "/ˈleɪtnt/", "zh": "adj. 潜在的；潜伏的；隐藏的" },
  { "en": "underlying", "phonetic": "/ˌʌndərˈlaɪɪŋ/", "zh": "adj. 潜在的；根本的；在下面的；优先的 v. 放在…的下面；为…的基础；优先" },
  { "en": "bizarre", "phonetic": "/bɪˈzɑːr/", "zh": "adj. 奇异的（指态度，容貌，款式等）" },
  { "en": "shabby", "phonetic": "/ˈʃæbi/", "zh": "adj. 破旧的；卑鄙的；吝啬的；低劣的" },
  { "en": "barren", "phonetic": "/ˈbærən/", "zh": "adj. 贫瘠的；不生育的；无益的；沉闷无趣的；空洞的 n. 荒地" },
  { "en": "weary", "phonetic": "/ˈwɪri/", "zh": "adj. 疲倦的；厌烦的；令人厌烦的 vi. 疲倦；厌烦 vt. 使疲倦；使厌烦" },
  { "en": "anonymous", "phonetic": "/əˈnɑːnɪməs/", "zh": "adj. 匿名的，无名的；无个性特征的" },
  { "en": "muddy", "phonetic": "/ˈmʌdi/", "zh": "adj. 泥泞的；模糊的；混乱的 vt. 使污浊；使沾上泥；把…弄糊涂 vi. 变得泥泞；沾满烂泥" },
  { "en": "productive", "phonetic": "/prəˈdʌktɪv/", "zh": "adj. 能生产的；生产的，生产性的；多产的；富有成效的" },
  { "en": "masculine", "phonetic": "/ˈmæskjəlɪn/", "zh": "adj. 男性的；阳性的；男子气概的 n. 男性；阳性，阳性词" },
  { "en": "explicit", "phonetic": "/ɪkˈsplɪsɪt/", "zh": "adj. 明确的；清楚的；直率的；详述的" },
  { "en": "nominal", "phonetic": "/ˈnɑːmɪnl/", "zh": "adj. 名义上的；有名无实的；[会计] 票面上的 n. [语] 名词性词" },
  { "en": "extinct", "phonetic": "/ɪkˈstɪŋkt/", "zh": "adj. 灭绝的，绝种的；熄灭的 vt. 使熄灭" },
  { "en": "slim", "phonetic": "/slɪm/", "zh": "adj. 苗条的；修长的；微小的；差的 vt. 使…体重减轻；使…苗条 vi. 减轻体重；变细" },
  { "en": "immune", "phonetic": "/ɪˈmjuːn/", "zh": "adj. 免疫的；免于……的，免除的 n. 免疫者；免除者" },
  { "en": "diffuse", "phonetic": "/dɪˈfjuːs/", "zh": "adj. 弥漫的；散开的 vt. 扩散；传播；漫射 vi. 传播；四散" },
  { "en": "aesthetic", "phonetic": "/esˈθetɪk/", "zh": "adj. 美的；美学的；审美的，具有审美趣味的 n. 审美；美学" },
  { "en": "reckless", "phonetic": "/ˈrekləs/", "zh": "adj. 鲁莽的，不顾后果的；粗心大意的" },
  { "en": "prevalent", "phonetic": "/ˈprevələnt/", "zh": "adj. 流行的；普遍的，广传的" },
  { "en": "interim", "phonetic": "/ˈɪntərɪm/", "zh": "adj. 临时的，暂时的；中间的；间歇的 n. 过渡时期，中间时期；暂定" },
  { "en": "consecutive", "phonetic": "/kənˈsekjətɪv/", "zh": "adj. 连贯的；连续不断的" },
  { "en": "discrete", "phonetic": "/dɪˈskriːt/", "zh": "adj. 离散的，不连续的 n. 分立元件；独立部件" },
  { "en": "sober", "phonetic": "/ˈsoʊbər/", "zh": "adj. 冷静的，清醒的；未醉的 vt. 使严肃；使醒酒，使清醒" },
  { "en": "cumulative", "phonetic": "/ˈkjuːmjəleɪtɪv/", "zh": "adj. 累积的" },
  { "en": "tolerant", "phonetic": "/ˈtɑːlərənt/", "zh": "adj. 宽容的；容忍的；有耐药力的" },
  { "en": "spacious", "phonetic": "/ˈspeɪʃəs/", "zh": "adj. 宽敞的，广阔的；无边无际的" },
  { "en": "verbal", "phonetic": "/ˈvɜːrbl/", "zh": "adj. 口头的；言语的；动词的；照字面的 n. 动词的非谓语形式" },
  { "en": "spatial", "phonetic": "/ˈspeɪʃl/", "zh": "adj. 空间的；存在于空间的；受空间条件限制的" },
  { "en": "practicable", "phonetic": "/ˈpræktɪkəbl/", "zh": "adj. 可用的；行得通的；可实行的" },
  { "en": "suspicious", "phonetic": "/səˈspɪʃəs/", "zh": "adj. 可疑的；怀疑的；多疑的" },
  { "en": "dubious", "phonetic": "/ˈduːbiəs/", "zh": "adj. 可疑的；暧昧的；无把握的；半信半疑的" },
  { "en": "edible", "phonetic": "/ˈedəbl/", "zh": "adj. 可食用的 n. 食品；食物" },
  { "en": "wretched", "phonetic": "/ˈretʃɪd/", "zh": "adj. 可怜的；卑鄙的；令人苦恼或难受的" },
  { "en": "pathetic", "phonetic": "/pəˈθetɪk/", "zh": "adj. 可怜的，悲哀的；感伤的；乏味的" },
  { "en": "intelligible", "phonetic": "/ɪnˈtelɪdʒəbl/", "zh": "adj. 可理解的；明了的；仅能用智力了解的" },
  { "en": "homogeneous", "phonetic": "/ˌhoʊməˈdʒiːniəs/", "zh": "adj. 均匀的；[数] 齐次的；同种的；同类的，同质的" },
  { "en": "sheer", "phonetic": "/ʃɪr/", "zh": "adj. 绝对的；透明的；峻峭的；纯粹的 adv. 完全；陡峭地 vi. 偏航 vt. 使偏航；使急转向" },
  { "en": "n.", "phonetic": "", "zh": "偏航；透明薄织物" },
  { "en": "rectangular", "phonetic": "/rekˈtæŋɡjələr/", "zh": "adj. 矩形的；成直角的" },
  { "en": "exquisite", "phonetic": "/ɪkˈskwɪzɪt/", "zh": "adj. 精致的；细腻的；优美的，高雅的；异常的；剧烈的 n. 服饰过于讲究的男子" },
  { "en": "shrewd", "phonetic": "/ʃruːd/", "zh": "adj. 精明的；狡猾的；机灵的 n. 精明（的人）；机灵（的人）" },
  { "en": "empirical", "phonetic": "/ɪmˈpɪrɪkl/", "zh": "adj. 经验主义的，完全根据经验的；实证的" },
  { "en": "metallic", "phonetic": "/məˈtælɪk/", "zh": "adj. 金属的，含金属的" },
  { "en": "concise", "phonetic": "/kənˈsaɪs/", "zh": "adj. 简明的，简洁的" },
  { "en": "curt", "phonetic": "/kɜːrt/", "zh": "adj. 简短而失礼的，唐突无礼的；简略的，简要的；草率的" },
  { "en": "straightforward", "phonetic": "/ˌstreɪtˈfɔːrwərd/", "zh": "adj. 简单的；坦率的；明确的；径直的 adv. 直截了当地；坦率地" },
  { "en": "compatible", "phonetic": "/kəmˈpætəbl/", "zh": "adj. 兼容的；能共处的；可并立的" },
  { "en": "intermittent", "phonetic": "/ˌɪntərˈmɪtənt/", "zh": "adj. 间歇的；断断续续的；间歇性" },
  { "en": "sturdy", "phonetic": "/ˈstɜːrdi/", "zh": "adj. 坚定的；强健的；健全的 n. 羊晕倒病" },
  { "en": "quarterly", "phonetic": "/ˈkwɔːrtərli/", "zh": "adj. 季度的，按季度的；一年四次的 adv. 按季度，[农] 一季一次地；纵横四分地 n. 季" },
  { "en": "terrific", "phonetic": "/təˈrɪfɪk/", "zh": "adj. 极好的；极其的，非常的；可怕的" },
  { "en": "superb", "phonetic": "/suːˈpɜːrb/", "zh": "adj. 极好的；华丽的；宏伟的" },
  { "en": "polar", "phonetic": "/ˈpoʊlər/", "zh": "adj. 极地的；两极的；正好相反的 n. 极面；极线" },
  { "en": "timely", "phonetic": "/ˈtaɪmli/", "zh": "adj. 及时的；适时的 adv. 及时地；早" },
  { "en": "drastic", "phonetic": "/ˈdræstɪk/", "zh": "adj. 激烈的；猛烈的 n. 烈性泻药" },
  { "en": "radical", "phonetic": "/ˈrædɪkl/", "zh": "adj. 激进的；根本的；彻底的 n. 基础；激进分子；[物化] 原子团；[数] 根数" },
  { "en": "integral", "phonetic": "/ˈɪntɪɡrəl/", "zh": "adj. 积分的；完整的，整体的；构成整体所必须的 n. 积分；部分；完整" },
  { "en": "muscular", "phonetic": "/ˈmʌskjələr/", "zh": "adj. 肌肉的；肌肉发达的；强健的" },
  { "en": "obscure", "phonetic": "/əbˈskjʊr/", "zh": "adj. 昏暗的，朦胧的；晦涩的，不清楚的；隐蔽的；不著名的，无名的 vt. 使…模糊不" },
  { "en": "pregnant", "phonetic": "/ˈpreɡnənt/", "zh": "adj. 怀孕的；富有意义的" },
  { "en": "skeptical", "phonetic": "/ˈskeptɪkl/", "zh": "adj. 怀疑的；（哲学）怀疑论的，不可知论的" },
  { "en": "gorgeous", "phonetic": "/ˈɡɔːrdʒəs/", "zh": "adj. 华丽的，灿烂的；极好的" },
  { "en": "reciprocal", "phonetic": "/rɪˈsɪprəkl/", "zh": "adj. 互惠的；相互的；倒数的，彼此相反的 n. [数] 倒数；互相起作用的事物" },
  { "en": "gloomy", "phonetic": "/ˈɡluːmi/", "zh": "adj. 黑暗的；沮丧的；阴郁的" },
  { "en": "legitimate", "phonetic": "/lɪˈdʒɪtɪmət/", "zh": "adj. 合法的；正当的；合理的；正统的 vt. 使合法；认为正当（等于legitimize）" },
  { "en": "militant", "phonetic": "/ˈmɪlɪtənt/", "zh": "adj. 好战的 n. 富有战斗性的人；好斗者；激进分子" },
  { "en": "implicit", "phonetic": "/ɪmˈplɪsɪt/", "zh": "adj. 含蓄的；暗示的；盲从的" },
  { "en": "scared", "phonetic": "/skerd/", "zh": "adj. 害怕的 v. 使害怕（scare的过去分词）" },
  { "en": "deliberate", "phonetic": "/dɪˈlɪbərət/", "zh": "adj. 故意的；深思熟虑的；从容的 vt. 仔细考虑；商议" },
  { "en": "stationary", "phonetic": "/ˈsteɪʃəneri/", "zh": "adj. 固定的；静止的；定居的；常备军的 n. 不动的人；驻军" },
  { "en": "eccentric", "phonetic": "/ɪkˈsentrɪk/", "zh": "adj. 古怪的，反常的 n. 古怪的人" },
  { "en": "solitary", "phonetic": "/ˈsɑːləteri/", "zh": "adj. 孤独的；独居的 n. 独居者；隐士" },
  { "en": "republican", "phonetic": "/rɪˈpʌblɪkən/", "zh": "adj. 共和国的；共和政体的；共和主义的；拥护共和政体的 n. 共和主义者" },
  { "en": "offensive", "phonetic": "/əˈfensɪv/", "zh": "adj. 攻击的；冒犯的；无礼的；讨厌的 n. 攻势；攻击" },
  { "en": "vocal", "phonetic": "/ˈvoʊkl/", "zh": "adj. 歌唱的；声音的，有声的 adj. 直言不讳的 n. 声乐作品；元音" },
  { "en": "lofty", "phonetic": "/ˈlɔːfti/", "zh": "adj. 高的；崇高的；高级的；高傲的" },
  { "en": "imaginative", "phonetic": "/ɪˈmædʒɪnətɪv/", "zh": "adj. 富于想象的；有创造力的" },
  { "en": "intricate", "phonetic": "/ˈɪntrɪkət/", "zh": "adj. 复杂的；错综的，缠结的" },
  { "en": "corrupt", "phonetic": "/kəˈrʌpt/", "zh": "adj. 腐败的，贪污的；堕落的 vt. 使腐烂；使堕落，使恶化 vi. 堕落，腐化；腐烂" },
  { "en": "subsidiary", "phonetic": "/səbˈsɪdieri/", "zh": "adj. 辅助的，次要的；附属的；子公司的 n. 子公司；辅助者" },
  { "en": "prone", "phonetic": "/proʊn/", "zh": "adj. 俯卧的；有…倾向的，易于…的" },
  { "en": "radiant", "phonetic": "/ˈreɪdiənt/", "zh": "adj. 辐射的；容光焕发的；光芒四射的 n. 光点；发光的物体" },
  { "en": "insane", "phonetic": "/ɪnˈseɪn/", "zh": "adj. 疯狂的；精神病的；极愚蠢的" },
  { "en": "cynical", "phonetic": "/ˈsɪnɪkl/", "zh": "adj. 愤世嫉俗的；冷嘲的" },
  { "en": "indignant", "phonetic": "/ɪnˈdɪɡnənt/", "zh": "adj. 愤愤不平的；义愤的" },
  { "en": "foul", "phonetic": "/faʊl/", "zh": "adj. 犯规的；邪恶的；污秽的；淤塞的 vt. 犯规；弄脏；淤塞；缠住，妨害 vi. 犯规；腐烂；缠" },
  { "en": "mortal", "phonetic": "/ˈmɔːrtl/", "zh": "adj. 凡人的；致死的；终有一死的；不共戴天的 n. 人类，凡人" },
  { "en": "luminous", "phonetic": "/ˈluːmɪnəs/", "zh": "adj. 发光的；明亮的；清楚的" },
  { "en": "vicious", "phonetic": "/ˈvɪʃəs/", "zh": "adj. 恶毒的；恶意的；堕落的；有错误的；品性不端的；剧烈的" },
  { "en": "redundant", "phonetic": "/rɪˈdʌndənt/", "zh": "adj. 多余的，过剩的；被解雇的，失业的；冗长的，累赘的" },
  { "en": "versatile", "phonetic": "/ˈvɜːrsətl/", "zh": "adj. 多才多艺的；通用的，万能的；多面手的" },
  { "en": "blunt", "phonetic": "/blʌnt/", "zh": "adj. 钝的，不锋利的；生硬的；直率的 vt. 使迟钝" },
  { "en": "transient", "phonetic": "/ˈtrænʃnt/", "zh": "adj. 短暂的；路过的 n. 瞬变现象；过往旅客；候鸟" },
  { "en": "turbulent", "phonetic": "/ˈtɜːrbjələnt/", "zh": "adj. 动荡的；湍流的；与紊流有关的" },
  { "en": "orthodox", "phonetic": "/ˈɔːrθədɑːks/", "zh": "adj. 东正教派的；正教的 n. 东正教徒；正教徒 adj. (orthodax) 正统的；传统的；惯常" },
  { "en": "oriental", "phonetic": "/ˌɔːriˈentl/", "zh": "adj. 东方的；东方人的 n. 东方人" },
  { "en": "qualitative", "phonetic": "/ˈkwɑːlɪteɪtɪv/", "zh": "adj. 定性的；质的，性质上的" },
  { "en": "quantitative", "phonetic": "/ˈkwɑːntəteɪtɪv/", "zh": "adj. 定量的；量的，数量的" },
  { "en": "imperial", "phonetic": "/ɪmˈpɪriəl/", "zh": "adj. 帝国的；皇帝的；至高无上的；威严的 n. 纸张尺寸；特等品" },
  { "en": "timid", "phonetic": "/ˈtɪmɪd/", "zh": "adj. 胆小的；羞怯的" },
  { "en": "massive", "phonetic": "/ˈmæsɪv/", "zh": "adj. 大量的；巨大的，厚重的；魁伟的" },
  { "en": "metropolitan", "phonetic": "/ˌmetrəˈpɑːlɪtən/", "zh": "adj. 大都市的；大主教辖区的；宗主国的 n. 大城市人；大主教；宗主国的公" },
  { "en": "erroneous", "phonetic": "/ɪˈroʊniəs/", "zh": "adj. 错误的；不正确的" },
  { "en": "vulgar", "phonetic": "/ˈvʌlɡər/", "zh": "adj. 粗俗的；通俗的；本土的 n. 平民，百姓" },
  { "en": "provocative", "phonetic": "/prəˈvɑːkətɪv/", "zh": "adj. 刺激的，挑拨的；气人的 n. 刺激物，挑拨物；兴奋剂" },
  { "en": "supersonic", "phonetic": "/ˌsuːpərˈsɑːnɪk/", "zh": "adj. 超音速的；超声波的 n. 超音速；超声波" },
  { "en": "trivial", "phonetic": "/ˈtrɪviəl/", "zh": "adj. 不重要的，琐碎的；琐细的" },
  { "en": "opaque", "phonetic": "/oʊˈpeɪk/", "zh": "adj. 不透明的；不传热的；迟钝的 n. 不透明物 vt. 使不透明；使不反光" },
  { "en": "indefinite", "phonetic": "/ɪnˈdefɪnət/", "zh": "adj. 不确定的；无限的；模糊的" },
  { "en": "incredible", "phonetic": "/ɪnˈkredəbl/", "zh": "adj. 不能相信的，难以置信的；极好的，极大的" },
  { "en": "adverse", "phonetic": "/ədˈvɜːrs,ˈædvɜːrs/", "zh": "adj. 不利的；相反的；敌对的（名词adverseness，副词adversely）" },
  { "en": "irrespective", "phonetic": "/ˌɪrɪˈspektɪv/", "zh": "adj. 不考虑的，不顾的 adv. 不考虑地，不顾地" },
  { "en": "supplementary", "phonetic": "/ˌsʌplɪˈmentri/", "zh": "adj. 补充的；追加的 n. 补充者；增补物" },
  { "en": "lame", "phonetic": "/leɪm/", "zh": "adj. 跛足的；僵痛的；不完全的；无说服力的；差劲的，蹩脚的 vi. 变跛 vt. 使跛；使成残" },
  { "en": "imperative", "phonetic": "/ɪmˈperətɪv/", "zh": "adj. 必要的，不可避免的；紧急的；命令的，专横的；势在必行的；[语]祈使的 n." },
  { "en": "intrinsic", "phonetic": "/ɪnˈtrɪnzɪk/", "zh": "adj. 本质的，固有的" },
  { "en": "exempt", "phonetic": "/ɪɡˈzempt/", "zh": "adj. 被免除（责任或义务）的，获豁免的 v. 免除，豁免 n. 被免除义务者（尤指被免税" },
  { "en": "tragic", "phonetic": "/ˈtrædʒɪk/", "zh": "adj. 悲剧的；悲痛的，不幸的" },
  { "en": "inclusive", "phonetic": "/ɪnˈkluːsɪv/", "zh": "adj. 包含的，包括的；包含全部费用的；" },
  { "en": "patriotic", "phonetic": "/ˌpeɪtriˈɑːtɪk/", "zh": "adj. 爱国的" },
  { "en": "periodical", "phonetic": "/ˌpɪriˈɑːdɪkl/", "zh": "adj. [数] 周期的；定期的 n. 期刊；杂志" },
  { "en": "random", "phonetic": "/ˈrændəm/", "zh": "adj. [数] 随机的；任意的；胡乱的 n. 随意 adv. 胡乱地" },
  { "en": "virtual", "phonetic": "/ˈvɜːrtʃuəl/", "zh": "adj. [计] 虚拟的；实质上的，事实上的（但未在名义上或正式获承认）" },
];